### ISSUE TITLE
qt theming.

### ISSUE THREAD

**Issue by barkingbandicoot** [bit-team/backintime#1031]
A small and petty thing perhaps but why does Back In Time as a QT app not respect my theming when opened as root?
I am running a dark themed Kubuntu but Back In Time as root is a light themed Ubuntu look.
Thanks!

nb the non-root app opens with theming, ran but 'with errors' .dbus ??

**Comment by shervinsahba** [comment]
root doesn't access your user's QT settings to prevent corrupting them. It won't even load its own QT theme, since it's operating within the environment of another user, so it falls back on some default.

You can run the program with `sudo -E backintime-qt`, though. This will to export your user's environment variables, including all the KDE ones. 

Warning, though. I've read that `sudo` should be used with caution with graphical applications, and that more restrictive alternatives like `kdesu` ought to be used instead. So, you may want to read up on the topic before throwing `sudo -E` at everything.
