### ISSUE TITLE
backintime broke my system - cannot login to Mint

### ISSUE THREAD

**Issue by MarkoPetteri** [bit-team/backintime#1034]
I wrote about this to Linux Mint Forum, but I thought this might interest some people here too

- Was making a snapshot with Back In Time
- Ran out of disk space while the snapshot was being made
- Restarted computer after finding no other way of stopping Back In Time from making the snapshot
- Now unable to login to my Mint account

When booting I enter disk decrypt password like usual but then when Mint starts, instead of auto-login to desktop it prompts me for user password. When I enter my password it just keeps coming back to the login screen like nothing happened.

Currently running Mint from a USB-stick. I tried to look at my filesystem but it says Unable to Mount.

**Comment by MarkoPetteri** [comment]
Reason for system breaking was low disk space.

I still think there should be a safe way to stop a snapshot for being made though!

**Comment by Germar** [comment]
So you made a snapshot to the same disk like your home folder? That's not a good idea because if your drive get corrupted you will loose both, your home folder and your backup of your home...

Linux behave quite strange when the home folder run out of space. But that has nothing to do with BiT

Btw pause and stop a current snapshot is implemented in 1.2.0
