### ISSUE TITLE
Can I remove select files?

### ISSUE THREAD

**Issue by wolftune** [bit-team/backintime#1047]
I don't want to remove an entire snapshot, but one of the directories has very large files I know I don't need. I'd like to exclude the old snapshots without excluding future backups of the directory.

In other words, is there a way to remove select files or directories from older snapshots?

**Comment by daveTheOldCoder** [comment]
My understanding is that it's perfectly safe to manually delete files or directories from snapshots, using a file manager or the command shell. I just tested it on a file, and it worked with no apparent adverse effects.

I used "sudo", since BIT makes the snapshot contents read-only.

If my understanding is wrong, please correct me.

**Comment by emtiu** [comment]
Manually removing the files is probably safe, but backintime also allows you to do this natively: through the "Snapshots" dialog when you have selected a file or folder in the main window. (It's the button next to the restore button.)
