### ISSUE TITLE
Non default ssh port

### ISSUE THREAD

**Issue by Sefi78** [bit-team/backintime#1056]
I have a Synology NAS, I started to back up my data weeks ago without any issues. But to avoid the security risk messages due to enabled ssh on default port on Synology, I have tried to change the port without luck. The error message is the following:

Remote host 192.168.1.22 doesn't support 
'['rsync', '--recursive', '--times', '--devices', '--specials', '--hard-links', '--human-readable', '--checksum', '--links', '--perms', '--executability', '--group', '--owner', '--port=1001', '--rsh=ssh -o ServerAliveInterval=240 -o LogLevel=Error -o IdentityFile=/home/tseffer/.ssh/id_rsa -p 1001', '/tmp/tmpb6xjz7ff/a', 'admin@192.168.1.22:"./tmp_7LWFL4"/']':
Permission denied, please try again.
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(235) [sender=3.1.2]

If I put back the default port, everything works well.

Thanks
Tamas

**Comment by juanluisbaptiste** [comment]
I'm getting the same error, I run the ssh service on my Synology NAS on a port different to port 22. I had checked that all the rsync options from the error message were supported by rsync command and they were, so I was really wondering what was generating this permission denied error.

**Comment by juanluisbaptiste** [comment]
But in my case switching the NAS ssh port back to 22 does not help, I still get that error. @Sefi78 could you share your configuration steps ? I already had public key ssh access working from my laptop to the NAS, I just installed latest backintime and configured the ssh mode connection, filling all the fields, is there some trick to it ?

**Comment by Sefi78** [comment]
Not sure, if all steps are required:

- set rsync port to the same as SSH
- enalbe sftp on the same port as SSH
- check rsync accounts
-
![image](https://user-images.githubusercontent.com/59749226/131583299-365d8f40-3765-4003-a265-68a0f9e2e5f7.png)

**Comment by juanluisbaptiste** [comment]
@Sefi78, thanks for the tips, I got it working. For anyone that stumbles on this, this is what I had to do to get backintime working with my Synology NAS:

1. Grant access to my user to the FTP application (control panel -> User (your user) -> Applications).
2. Make sure SFTP support is enabled _and_ working (Control panel -> File Services -> FTP). Also, for me it wasn't enough just to enable sftp support on DSM control panel, I also had to modify the `/etc/ssh/sshd_config` file and change the sftp subsystem configuration:

```
# override default of no subsystems
#Subsystem  sftp    /usr/libexec/sftp-server
Subsystem       sftp    internal-sftp -f DAEMON -u 000
```
Use the second line instead of the first one, with the first one I would get a `Connection closed` when doing a sftp to the NAS or `remote host has dsconnected` when using `sshfs` to mount a remote directory from the NAS. If you can connect via sftp or do an sshfs mount then sftp is working correctly and any other issue is something else (see below).

3. Enable rsync support (Control panel -> File Services -> rsync)
4. Use a ssh private key with password, for some reason backintime would not allow me to use a password-less private key.

One thing that helped me debug this was to uncheck the "Check if remote hosts support all necessary commands", at some point it seems that was enmasquerading another error with the ssh not running, so also make sure the ssh-agent is running. I think backintime starts it but when doing all the tests I manually killed it and backintime did not start it again when relaunched afterwards.

PS: I do not understand why you posted the settings for a rule for _NFS_ access ? we are taking about ssh.

**Comment by Sefi78** [comment]
Correct,  I have tried several things until get working and as I wrote you might not need all the settings. I have removed that point. Finally it is working for you :)
