### ISSUE TITLE
Error: rsync: symlink failed: Function not implemented (38)

### ISSUE THREAD

**Issue by ventolinmono** [bit-team/backintime#1057]
Getting several errors of this kind:
`[E] Error: rsync: symlink "/media/veracrypt1/backintime/computer/user/1/new_snapshot/backup/home/user/.thunderbird" -> "/home/user/.icedove" failed: Function not implemented (38)`

There's not much info in the docs about errors.

**Comment by jtuckerk** [comment]
*very speculative*
This may be due to using the wrong filesystem type. I partitioned a usb to have an exfat partition and an ext4 partition. I meant to put my backintime backups on the ext4 partition, but accidentally backed up to the exfat partition. it was slow and had lots of the above error. changing the backup to the ext4 partition was faster and error free.

**Comment by jdalbey** [comment]
I'm getting these errors also, and I'm not doing anything unusual with filesystem types. Using BiT 1.3.2.  I note a lot of the messages are on binary library files, e.g. `.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu/libcap.so.2" -> "libcap.so.2.22" failed: Function not implemented (38)`

**Comment by jdalbey** [comment]
Solved! (For me anyway).  These errors were happening because I was trying to backup to an external USB drive that was formatted as FAT32.  I reformatted the drive to ext4 and the backup completed without error.

**Comment by emtiu** [comment]
Yes, that would be the expected result, beause just as rsync reports: symlinks are not supported by FAT32 (`Function not implemented`). Thanks for reporting back, closing the issue!
