### ISSUE TITLE
restore only a single file

### ISSUE THREAD

**Issue by Golddouble** [bit-team/backintime#1065]
Scenario:
At 2020-01-01 I made a backup of the whole home folder.
At 2020-01-02 I have by mistake deleted the file MyFile, which was in my home folder.

Can I now restore only this particular file using the gui of backintime? Or is the only possibility to use a terminal for such a situation? (I searched in the documentation, but did not find the answer of this question there by sure. Maybe we can simply mark a particular file and press restore?)

Thank you.

**Comment by hannes101** [comment]
https://backintime.readthedocs.io/en/latest/mainwindow.html#files-view 
Well, isn't that kind of self-explanatory if you browse the backup you can of course select single files and with a right-click it's possible to restore the file.

**Comment by pbulteel** [comment]
> https://backintime.readthedocs.io/en/latest/mainwindow.html#files-view
> Well, isn't that kind of self-explanatory if you browse the backup you can of course select single files and with a right-click it's possible to restore the file.

Not only that, but when you're restoring you can restore to a completely different location. This would be helpful in the case you don't want to overwrite a file -- say in the example above, instead of deleting the file, you overwrite it. Now you want to restore a copy of the backup file so you can compare the two...

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Close
