### ISSUE TITLE
re-occuring backup not working

### ISSUE THREAD

**Issue by richb201** [bit-team/backintime#1066]
I have Back in Time set up to back up certain dirs every night at midnight. But looking at the attached screen shot that doesn't appear to be happening. Why? Is there a log I need to check to debug?
![Screenshot from 2020-02-13 09-12-33](https://user-images.githubusercontent.com/6951833/74443413-1f1c2380-4e41-11ea-852b-2b7f711f1541.png)
![Screenshot from 2020-02-13 09-09-55](https://user-images.githubusercontent.com/6951833/74443423-23e0d780-4e41-11ea-8c3e-bd5fbba9594d.png)

**Comment by emtiu** [comment]
Hi—a snapshot will be skipped if the files haven't changed since the last snapshot. It's possible that's what was happening. Since version 1.1.4, there is an option to take snapshots anyway (_"Take a new snapshot regardless of there were changes or not."_).

Did you ever find out what was going on, is this problem still relevant to you?

**Comment by emtiu** [comment]
Closing, since the reporter is not responding.
