### ISSUE TITLE
Help with Key

### ISSUE THREAD

**Issue by wes1993** [bit-team/backintime#1076]
Hello to everyone!! 
I'm trying to uuse this beautiful software with my Buffalo NAS (i can enable FTP, SFTP, RSYNC, NFS).
But i can't copy the .pub key and i can only add a .crt and .key file.. there i a way to use the ssh?
Thanks a lot
Stefano

**Comment by emtiu** [comment]
Hi, thanks for your question. It looks like this problem is not specific to backintime, but related to the general question of passwordless SSH with key authentication. You'll find plenty of howtos online on how to set this up. If you still have questions about backintime later, feel free to open another Issue here.
