### ISSUE TITLE
Deleting old snapshots to make room for new

### ISSUE THREAD

**Issue by djpeter84** [bit-team/backintime#1080]
I have a 1T External hard drive but it is now getting full. If i want to delete old backintime backups to save space for new ones, do i delete the oldest backup or the most current?

Thanks.

**Comment by daveTheOldCoder** [comment]
Delete whichever ones you don't want to keep.

**Comment by Sarke** [comment]
Keep in mind that you might not free up as much space as the OS reports the folder to be.  If those files are hard linked from another snapshot, they won't be removed from the disk.

**Comment by katian** [comment]
try `ncdu` under CLI

**Comment by Sarke** [comment]
@katian `ncdu` doesn't handle hard links in a way that it will show the correct reclaimable disk space.

**Comment by daveTheOldCoder** [comment]
The FAQ provides this command to correctly see the disk space usage of the snapshots:
`du -chd0 /media/<USER>/backintime/<HOST>/<USER>/1/*`

**Comment by molleJoe** [comment]
No, this command doesn't work.
'du -dhd0 /media/<USER>/backintime/<HOST>/<USER>/1/*' looks nice, but I think, it doesn't shows the actual disk space, used by single snapshots.

Real example (1st, 2nd and 3rd line of output of 'du -dhd0 /media/joerg/BackupWeiss/backintime/uhu2/root/1/*'):
  192G    /media/joerg/BackupWeiss/backintime/uhu2/root/1/20160512-204503-121
  105M    /media/joerg/BackupWeiss/backintime/uhu2/root/1/20160513-202433-620
  521M    /media/joerg/BackupWeiss/backintime/uhu2/root/1/20160516-223230-177
  ...

First output line shows a really huge size, because 'du -dhd0' command doesn't have a "reference", before.
Second line is much smaller (only difference to 1st line).
But if you delete 1st backup, you will free much less than 192G! This is, because a lot of files are linked at 2nd (and later) snapshot(s), of course.
Even size of second snapshot will be wrong, because a lot of files will be linked at later snapshots.

I have another proposal, showing which space will be freed, if you delete a given snapshot.
The idea is to only add size of each file with link count **1** (using find's parameter '-links'). Unfortunately it's not a one liner:

snapshot="/media/joerg/BackupWeiss/backintime/uhu2/root/1/20160512-204503-121"
export sumkilos=0
find "$snapshot" -links 1 -print0 \
| ( while read -d $'\0' file ; do
        sumkilos=$(($sumkilos + $(du -k "$file" | cut --fields=1)))
    done
    echo Backup uses $(($sumkilos/1024)) MiByte
)

This results in 843 MiByte at my example, while your 'du -dhd0' command talks about 200 times bigger size ...
And also at 2nd snapshot: it's really 34 MiByte, not 105M (obviously some files are linked at later snapshots).

Of course it can be extended to show sizes of all single snapshots. But it makes not sense: The sum will be much less, because all files, are hardlinked >1 times, will not be listed. Or in other words, with deleting one snapshot, the results of other snapshots changes: If there files with link count 2, before - and deleting/unlinking such a file at deleted snapshot.

Should I create an issue, to change FAQ? Since FAQ is not at repository, I'm not sure.

**Comment by daveTheOldCoder** [comment]
I suppose "actual disk space used" is ambiguous when you're dealing with hard linked files. It depends on what you want to measure.

Adding an issue to change the FAQ probably won't accomplish anything, since no one seems to be responding to issues. Maybe you should just add the additional information to the FAQ yourself. It's apparently part of this github site, and there's an edit link.

**Comment by djpeter84** [comment]
I am trying to copy my BIT snapshots from one external hard drive (about 300G) to another. I have tried a few times and each time I try to copy the amount of space doubles or triples at the destination. The 300G i try to copy takes up about 600G plus on my new 2TB hard drive.

**Comment by daveTheOldCoder** [comment]
It sounds like hard links weren't preserved in the copy. Did you use one of the methods suggested in the FAQ entry "How to move snapshots to a new hard-drive?" ?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
When you move snapshots you should not use copy. You should use rsync for this with the right options to prevent links.

**Comment by emtiu** [comment]
Closing this Issue, the discussion about space continues in #406.
