### ISSUE TITLE
Is BackInTime dead?

### ISSUE THREAD

**Issue by DeaDSouL** [bit-team/backintime#1088]
Hi,
It looks like there wasn't any development recently.. even the issues section has so many new posts without any comment from the developers..
So, is BackInTime project dead?

I really hope it's not..

Thanks

**Comment by bit-user** [comment]
I asked myself the same question. I hope the maintainer @Germar didn't die of covid-19 :(

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Close please.

**Comment by colinl** [comment]
What is the point in closing this, unless someone is taking over support of this project?  It servers as a useful placeholder for anyone looking at issues here and hoping for support.

**Comment by rnc** [comment]
I don't fully understand why @Codeberg-AsGithubAlternative-buhtz  is putting `Close please` comments though-out - do you have admin rights on the project in which case you could close the issues and merge the PRs yourself?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
If I had admin rights I would close it myself.
Close because it is a duplicate. E.g. see #1114 

All respect to you. ❤️ 
There is no need to take over the project because it is still maintained.
I am full with understanding that this quesiton comes up from time to time.
But please respect the ressources and freetime of the maintainers.

@Germar I would suggest that you write a small text about the project status and how it is maintained in the FAQ or in the Readme.md. Then we could link to it everytime this questions comes up as an Issue.

**Comment by rnc** [comment]
@Codeberg-AsGithubAlternative-buhtz If you're not a maintainer (and there could be several on a project) then, with all due respect - and with no intend to offend -  it seems like you are 'spamming' issues with these comments? If you are part of the team why not request maintainer rights so you can close/update issues etc  - this would make things much easier wouldn't it?

**Comment by caco3** [comment]
> There is no need to take over the project because it is still maintained.

@Codeberg-AsGithubAlternative-buhtz I can not really believe this. As it seems, @Germar is the only one having admin rights, and his last commit was in [August 2019](https://github.com/bit-team/backintime/commits/master)! :unamused: 

I do not understand how you can call it **maintained**! the documentation is outdated and many parts of it do not apply anymore. There are 361 open issues and 8 pull requests and nobody except @Germar is able to process them.

**Comment by bit-user** [comment]
This project is just dead. I can only recommend everyone to migrate off, before a flaw in the code makes backups unusable and will never get fixed.

**Comment by caco3** [comment]
> This project is just dead. I can only recommend everyone to migrate off, before a flaw in the code makes backups unusable and will never get fixed.

I am using BiT since over 10 years. There is a huge trust into its stability from my side. A new tool first would have to gain this trust.
Beside of this, BiT uses rsync. The files are all accessible directly on the backup system. So even in the unlikely case BiT would stop working, you still would have access to your backups.

And even if so, BiT is open source, you could fork and fix it. 
The only reason I am not doing this (yet) is because it is well known, working as needed and a fork first would have to get adapted by the distro maintainers. Also its not helpful for novice Linux users to have to switch a tool just because there is now a newer one.

**Comment by bit-user** [comment]
> I am using BiT since over 10 years. There is a huge trust into its stability from my side.

Sure, but it was also maintained the past 10 years which is not the case anymore. But yeah, please go ahead and fork it and be the next maintainer. I am no coder, I am a user that doesn't trust his (backup) data to unmaintained software.

**Comment by Germar** [comment]
Hey guys, sorry for being off for so long. I'm quite busy in my job, found a new girlfriend and kind of lost interest in BiT. Sorry.
I'll try to maintain BiT better soon, but I need some time before I can start because I'm about to move my flat.
Please don't contact my friends or my work any more.

**Comment by colinl** [comment]
Great, glad to have you back :)

**Comment by caco3** [comment]
> I'll try to maintain BiT better soon

Please consider to open it so others can continue your great work!
I know other great tools which slowed down but then suddenly got new breath when new developers started to work on it (eg. https://github.com/cgeo/cgeo)

**Comment by emtiu** [comment]
The latest discussion on the state of the project took place in #1232.
