### ISSUE TITLE
test_readWriteCrontab fails when crontab is an empty file

### ISSUE THREAD

**Issue by willemw12** [bit-team/backintime#1181]
Test test_readWriteCrontab fails when crontab is an empty file.

    $ crontab -e

Save an empty crontab.

    $ crontab -l | wc -l
    0

    $ LC_ALL=en_US.UTF-8 make common test-v
    ...
    test_readWriteCrontab (test.test_tools.TestTools) ... FAIL
    ...
    Stdout:
    DEBUG: [common/tools.py:1237 readCrontab] Read 1 lines from users crontab
    DEBUG: [common/tools.py:1274 writeCrontab] Wrote 2 lines to users crontab
    DEBUG: [common/tools.py:1237 readCrontab] Read 1 lines from users crontab

**Comment by aryoda** [comment]
Congrats, perfect issue report with excellent minimal reproducible example :-)

I could reproduce the test failure on HEAD and Ubuntu 20.04 with Python 3.8.10 via `LC_ALL=en_US.UTF-8; make test-v`:

```
FAIL: test_readWriteCrontab (test.test_tools.TestTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/XXX/dev/backintime/common/test/test_tools.py", line 556, in test_readWriteCrontab
    self.assertEqual(len(newCrontab), len(oldCrontab) + 1)
AssertionError: 1 != 2

Stdout:
DEBUG: [common/tools.py:1237 readCrontab] Read 1 lines from users crontab
DEBUG: [common/tools.py:1274 writeCrontab] Wrote 2 lines to users crontab
DEBUG: [common/tools.py:1237 readCrontab] Read 1 lines from users crontab
```

Would be great if a developer here raises the hand to fix this (I have no more time this week), since it is so easy to reproduce...

**Comment by aryoda** [comment]
**Diagnoses:**

This code line creates a list of lines from the file content using the new line char (\n) to split the lines:

https://github.com/bit-team/backintime/blob/master/common/tools.py#L1236

If the crontab file is empty it returns a list of length 1 (sic!) with an empty string instead of an empty list:

`crontab = {list: 1}['']`

Instead an empty file should return a an empty list of length 0:

`[]`

I think the fix is easy so I will prepare one and open an pull request...

**Comment by aryoda** [comment]
Note: The unit test also fails if the crontab contains only empty lines (one or more) since this is also stripped and split into the erroneous `['']` (list of length 1 instead 0)
