### ISSUE TITLE
Will backintime sustain this double upgrade (distribution upgrade + backintime package upgrade)?

### ISSUE THREAD

**Issue by Enjymon** [bit-team/backintime#1185]
I had backintime 1.2.1 working on a Linux Mint 19.3 (based on Ubuntu 18.04) which I used to backup my Home directory on an external drive. (For some reason, I had missed the 1.2.1 -> 1.3.0 and 1.3.0 -> 1.3.1 upgrades of backintime, even though I had installed the bit-team/stable repository).

Now I have made a fresh upgrade of my system to Linux Mint 20.2 while preserving my Home directory partition. Upon reinstalling my software, I now have backintime 1.3.1 available for install.

If I install backintime 1.3.1, will it work smoothly with the backups on my external drive made with backintime 1.2.1? Will it be able to use the configuration files and resume any scheduled backup in my profile?

**Comment by aryoda** [comment]
@emtiu Add "documentation" label here?

**Comment by Enjymon** [comment]
For information, from lack of response I decided to start my backups anew, with a new profile in backintime 1.3.1 and a new destination folder so as not to mess up with the folder of my former backups data from backintime 1.2.1.

So now I have two destination folders: an old one (that I was using with backintime 1.2.1) and a new one (that I am using with backintime 1.3.1).

Is there a hack to merge them, or would it just make no sense at all to go along this path? (And actually, does backintime perform incremental or differential backups ? In the [main/welcome page](https://github.com/bit-team/backintime) there is a `incremental` tag, but further down only "differential" is [mentioned](https://github.com/bit-team/backintime#file-permissions-handling-and-therefore-possible-non-differential-backups))

**Comment by aryoda** [comment]
> So now I have two destination folders:
> an old one (with the backups from backintime 1.2.1 and that is not in use anymore)
> and a new one (that I am now using with backintime 1.3.1).
> 
> Is there a hack to merge them, or would it just make no sense at all to go along this path? (

Do the old backups overlap with the new backups (same snapshot times and same files)?
Then you may overwrite some files and I would refrain from doing that.

If not I would give it a try to merge them together into one folder.

There is documentation on how to move a backup folder. You could use this to copy your old folder into the new one
(take care to use the correct profile number in the target folder):

https://github.com/bit-team/backintime/wiki/FAQ#how-to-move-snapshots-to-a-new-hard-drive

Important:

- Check your profile settings regarding auto-remove of old snapshots (otherwise you may loose the old ones one day)
- Use the `rsync` method (`dd` is too dangerous and does not allow to merge folders as you want to)
- Keep your old folder and watch what happens in the new folder with your old snapshots

**Comment by buhtz** [comment]
Seems to me we can close this Issue?

**Comment by buhtz** [comment]
@Enjymon do you have something to add? Can we close the Issue for now?
