### ISSUE TITLE
Can BackInTime be used for system backups?

### ISSUE THREAD

**Issue by mYnDstrEAm** [bit-team/backintime#1211]
Can BiT be used to backup and restore system partitions, including system configurations and installed packages on Debian11/KDE, even if the target drive is a different one and has a different partition size?

How does it compare to alternatives? Basically `BackInTime` vs plain `rsync` vs `borg` vs `Timeshift` vs [`dd` clone](https://www.makeuseof.com/tag/2-methods-to-clone-your-linux-hard-drive/) vs `clonezilla` vs [`dump`](https://unix.stackexchange.com/questions/41399/system-image-of-running-debian-system) for restoring system partitions.

It would be best if the backups are done incrementally so things, already backed-up aren't backed up again.

And if it can be used for this, how would be the way to do so? For example, excluding the /proc directory and */node_modules, checking the "Preserve extended attributes (xattr)" setting in the "Expert Options" and keeping only very few (e.g. two) backups.

How exactly would one go about quickly and easily restoring the backup (when using a dd clone instead one can [restore the image](https://www.makeuseof.com/tag/easily-clone-restore-linux-disk-image-dd/))? It would be best if one doesn't need to reinstall Debian but could just restore the backup from a liveDVD. The /home directory is on a separate partition. Could using BiT be best practice / the best option for this use-case?

**Comment by mYnDstrEAm** [comment]
That's useful, thanks! However, I think this doesn't solve this part:

>And if it can be used for this, how would be the way to do so? For example, excluding the /proc directory and */node_modules, checking the "Preserve extended attributes (xattr)" setting in the "Expert Options" and keeping only very few (e.g. two) backups.
>
>How exactly would one go about quickly and easily restoring the backup (when using a dd clone instead one can [restore the image](https://www.makeuseof.com/tag/easily-clone-restore-linux-disk-image-dd/))? It would be best if one doesn't need to reinstall Debian but could just restore the backup from a liveDVD. The /home directory is on a separate partition. Could using BiT be best practice / the best option for this use-case?

Basically:

* Is there a tutorial or an exclude-include file somewhere that has the files you should backup to be able to run a complete full system restore (on Debian and similar)?
* Could the features described there, and there are probably many more that would be useful for full system backup&restore, be added to BiT in a native system B&R functionality?
Basically, making things as easy and fail-safe and quick as possible, so you have all your files backed up and the barrier to running full backups is low even for people who don't like to or can't tinker around...you simply have an option to run a full backup and an easy process for restoring it.

**Comment by emtiu** [comment]
> * Is there a tutorial or an exclude-include file somewhere that has the files you should backup to be able to run a complete full system restore (on Debian and similar)?

I'm sure that such guides exist, but I'm not aware of a specific one, and it's not part of backintime's documentation. Keep in mind that this would be highly distro-specific, because special directories and mountpoints like those under `/dev`, `/sys` and `/run` can be wildly different from one distro to another. IMHO, it would be nearly impossible for backintime to keep up with all (or even most) of them.

> * Could the features described there, and there are probably many more that would be useful for full system backup&restore, be added to BiT in a native system B&R functionality?
>   Basically, making things as easy and fail-safe and quick as possible, so you have all your files backed up and the barrier to running full backups is low even for people who don't like to or can't tinker around...you simply have an option to run a full backup and an easy process for restoring it.

The main goals/unique benefits of backintime (as I understand them) are:
1) to make the most of the powers of `rsync` in order to create incremental backups,
2) to provide a convenient and powerful graphical interface for browsing past snapshots and restoring from them,
3) and to store the backed up files in their original form and directory structure in a sane and easy-to-navigate set of folders, making it possible to restore from backup even without the backintime software itself.

This is a whole other game from complete-system backups, which need to deal with special mountpoints, device files, boot code etc. Take a look at [TimeShift](https://github.com/linuxmint/timeshift), though, it may be just what you're looking for, and from what I understand, it can even be used sensibly in combination with backintime.

**Comment by emtiu** [comment]
(Note that there is an open ticket relating to this exact discussion/feature request at #480.)
