### ISSUE TITLE
Why is OpenSSH a dependency?

### ISSUE THREAD

**Issue by dataprolet** [bit-team/backintime#1224]
I was simply wondering why OpenSSH is a dependency and not some other SSH implementation like e. g. TinySSH?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Are you referring to the dependency in the context of a debian package?

https://github.com/bit-team/backintime/blob/0ef26e1a52cc87875d89cea75de9d1298fb88bc1/debian/control#L12

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Is this Issue still relevant for you? Then please answer back (and re-open) it.

Package dependencies are handled by the distributions and shouldn't be handled by us (upstream). But in the current state there are debian-things in that repository. But this will be fixed and cleaned up.

Because of that I assume this Issue isn't relevant anymore and vote (@emtiu ) vor close.
