### ISSUE TITLE
Guide for a CLI Use Case

### ISSUE THREAD

**Issue by InklingGirl** [bit-team/backintime#1225]
Hey, is it possible for someone to write up a guide &/or–for my own convenience–help me out w/ using the CLI for this app? There's not really any good documentation on this, & the man page isn't super clear to me. I'd really love to use this in CLI though, so any help would be appreciated! Thank you.

**Comment by gsker** [comment]
The man page combined with the examples seems pretty complete, but you could probably make quicker headway if you fired up the graphical environment and configured some snapshots and ran them and then looked at the contents of the resulting config file in `~/.config/backintime/config`  
Also configure a scheduled job so you can see what ends up in the crontab.

Is there a specific thing you don't see in the included documentation?

**Comment by InklingGirl** [comment]
> you could probably make quicker headway if you fired up the graphical environment and configured some snapshots and ran them and then looked at the contents of the resulting config file in `~/.config/backintime/config`

I did just that, & the only contents in that file are:
```
config.version=6
profiles.version=1
```

**Comment by InklingGirl** [comment]
> /root/.config/backintime/config

Ah, yes, because I always run _Back in Time (root)_ from the GNOME Applications Menu, so all the content was located there & it looks much like your own `config.txt`. That being said, I'm not entirely sure how it helps me w/ using the CLI for this app. Could you please give an example of a command?

**Comment by gsker** [comment]
Sure.  Your example command is in cron because you did this: _Also configure a scheduled job so you can see what ends up in the crontab._ 
:-D

Here's my crontab line that matches the above attached config file:
* `0 20 * * * /usr/bin/nice -n19 /usr/bin/ionice -c2 -n7 /usr/bin/backintime --profile-id 2 backup-job >/dev/null 2>&1`
* The command part is  `/usr/bin/backintime --profile-id 2 backup-job`

It was created by scheduling the job in the UI. The manpage lists all the commands and the options associated with them.

I have written a simple user-callback script to manage different mount situations and to re-suspend the computer after backup if it had been woken up to do the backup.  But other than that I just set the settings using the UI.  

Given that you're seeing those configs end up in your user home, you might have to copy the config file over from your user to root's home.  Or jut run it as `/usr/bin/backintime --config ~inklinggirl/.config/backintime/config`.  It's possible that that will break things a little because root might overwrite it and change ownership so your user can't manage it.

**Comment by gsker** [comment]
Your backintime try did not include any command to run.  
And no profile to point to. 
The part of my response that you used was supposed to just indicate that you COULD point to the config file in a  different location.
### Run this command
* `backintime --help`

### The flow
1. In the GUI in General choose a path to store your snapshots. 
1. Also on the General tab notice under Advanced where it says "Full snapshot path"  That's where the snapshots will end up.
1. On the Include tab click Add Folder and navigate to the folder you want to back up. 
1. Exit the GUI
1  If you used the (root) startup then you have to run your backup as root
1. run this command  `sudo -i backintime --profile-id 1 backup`

This isn't a great use of backintime, though. 
backintime is for making ongoing backups of system paths.  And your use is an initial backup. 
rsync or tar would be better tools.

**Comment by InklingGirl** [comment]
Ah, OK I think understand @gsker, & `sudo -i backintime --profile-id 1 backup` works perfectly. So, would the profile (snapshot path) as you specify it be included in your config? If so, I could create one in advance & copy it over to a new system, right? Thank you.

**Comment by gsker** [comment]
Yes. You could. You are welcome! Please close this ticket if it's resolved.

**Comment by InklingGirl** [comment]
Alright, thank you.
