### ISSUE TITLE
Set up non-root version, but root-enabled version does not find the configuration

### ISSUE THREAD

**Issue by BrrrKnee2** [bit-team/backintime#1254]
I've had this backing up data for about 3 days, realized several critical files in my personal folders required root access, so these fail in the backup.  Luckily I found that the install also provided a root-capable app, but opening it did not find my BIT config.
I think it should, but in any case, where is the config file stored/maintained in the filesystem, so I can restore it into the root-capable app settings?  
Thank you!
Update 5/11: I found the config file, in my home directory within the hidden ".config" folder. Unfortunately, the "restore prior config" will not show that in the navigation, so where BIT saves it, it can not be found to restore.
Either offer hidden folders under the users' home directory (~/.config) or save config in a non-hidden folder.

**Comment by emtiu** [comment]
Take a look at `$HOME/.config/backintime/` for your regular-user configuration. It's normal that running as root would have a different configuration, probably stored in `/root/.config/backintime/`. This is very much the expected behavior.

Keep in mind that systems may have multiple users. A Linux system works by the principle of "many users, but just one root account". This explains the separate configuration.

You may be thinking in terms of "I'm the only user, and sometimes I'm also root", but that's not the way this (and lots of other software) was designed.
