### ISSUE TITLE
Questions - run multiple profiles in serial and others...

### ISSUE THREAD

**Issue by Whytey** [bit-team/backintime#1266]
Hi,

I have been successfully using BiT (common) for many years (in cmd line form on my server) - great product.   My `files` profile runs nightly at 1am - mostly it is a pretty quick run, unless I have uploaded a bunch of new digital photos or something.

My server also serves as a DB server and LXD container host and I would like to add 2 more profiles to my configuration and use BiT as part of my backup solution so I can use the smart remove feature to manage how many historical backups I keep:
- I would like to `mysqldump` every database nightly and then backup the `*.sql.gz` files.  Currently DB backups are about 1GB of discrete data.
- I would like also like to `lxc.export` my containers weekly and then backup the `*.tar.xz` files.  Current my ~10 containers require 40GB of disk per backup.

[**Note**: I acknowledge that BiT's space savings technique won't be realised since each file will be unique]

My general pseudo-code:
```
create a place to put the exported file [*1]
for each item (db or container):
  export the item [*2]
back up the export
clean up the exported items [*3]
```

I have some questions:

1. How could I ensure that the 3 profiles are run in serial?  Would I have to write a wrapper script for this?
2. How would you approach the external activity of doing the mysqldump or the lxc.export commands - callbacks from within the BiT run or more simply 
3. For note `[*1]` above, the easy way would be to create a folder in `/tmp` and put the items there.  Ideally, I would like to have something more transient and thought about using a tmpfs drive.  If it isn't transient, need to make sure the folder is unique each backup run, but I can't dynamically specify this `include.I.value` at execution time to BiT, can I.
4. For note `[*2]`, is it possible at all to run BiT multiple times but write files to the same timestamped backup?  For container backup, it would be ideal to to the backup after the export of each container rather than exporting them all before running BiT.
5. With regards to note `[*3]`, I need to ensure the files are cleaned up.  Are there any gotchas with running a callback script post backup?  Could there be occasions when it won't get run (backup failure)?

Thanks for your help.

**Comment by emtiu** [comment]
Hi! For most of what you want to do, backintime's [`user-callback`](https://github.com/bit-team/user-callback) feature is a good place to start. Read through the examples on the linked page to get an idea of how it works. It can be tricky to wrap your mind around, but it's easy to play around with and try out :)

> 1. How could I ensure that the 3 profiles are run in serial?  Would I have to write a wrapper script for this?

As far as I am aware, snapshots are normally taken in parallel if they're scheduled for the same time. Take a look at your crontab to see how backintime registers itself there.

To ensure waiting times before the actual snapshotting begins, you could include `sleep` commands in the user-callback script.
 
> 2. How would you approach the external activity of doing the mysqldump or the lxc.export commands - callbacks from within the BiT run or more simply

Also here, `user-callback` is probably the best place.

Alternatively, you could just define a custom cronjob to prepare your backup data – just make sure it has enough time to run, so it will be finished when the snapshotting starts.

> 3. For note `[*1]` above, the easy way would be to create a folder in `/tmp` and put the items there.  Ideally, I would like to have something more transient and thought about using a tmpfs drive.  If it isn't transient, need to make sure the folder is unique each backup run, but I can't dynamically specify this `include.I.value` at execution time to BiT, can I.

On most Linux systems, `/dev/shm` is a reasonably large tmpfs. You might use that if it has enough space, so you don't need to prepare a custom tmpfs mount.

In order to ensure different folders for different runs, a common strategy is to include the date/time in the folder name, like so: `mkdir backup-$(date +%Y%m%d-%k%M%S)`

To have a fixed reference point for the latest backup, you could have a symlink always pointing to the last-created folder:
```
NOW=$(date +%Y%m%d-%k%M%S)
mkdir backup-$NOW

[... do your backup ...]

ln -sf latest-backup backup-$NOW
```

backintime does the same with its `last-snapshot` symlink in its backup folders :)

> 4. For note `[*2]`, is it possible at all to run BiT multiple times but write files to the same timestamped backup?  For container backup, it would be ideal to to the backup after the export of each container rather than exporting them all before running BiT.

I'm pretty sure that's not possible. Each run will produce a new, separate snapshot.

> 5. With regards to note `[*3]`, I need to ensure the files are cleaned up.  Are there any gotchas with running a callback script post backup?  Could there be occasions when it won't get run (backup failure)?

The `user-callback` script also gets called on errors, so you might try and catch them and do some cleanup if necessary – but obviously, this is tricky to test in advance.

Again, an external, custom cronjob for cleanup might be a more robust solution.

> Thanks for your help.

Good luck! :) Kindly close this issue (and document your solution, if you like) when you get things working.

**Comment by Whytey** [comment]
Thanks for the reply. I'll get onto this over the next couple of days.

**Comment by Whytey** [comment]
I have half created my user-callback script - it is hosted on github at https://github.com/Whytey/bit-config/blob/main/user-callback

Closing :)
