### ISSUE TITLE
How to backup to disk connected on webdav protocol ?

### ISSUE THREAD

**Issue by kberkut** [bit-team/backintime#1314]
How to backup to disk connected on webdav protocol ?

**Comment by emtiu** [comment]
Hi, a webdav storage alone cannot be used as a snapshot target nativley. For remote storage, backintime needs ssh access and an rsync connection to the target machine.

You might try mounting the webdav to your local machine, and specifying the mountpoint as the target. I can't tell you how to do that exactly, but it's possible in principle. However, people often encounter problems with such setups, because backintime expects certain advanced filesystem features like hardlinks.

I'm closing this issue as "solved", but feel free to reply again if you have further questions :)
