### ISSUE TITLE
Write and publish "Installing backintime on CentOS 7 / 8" instructions

### ISSUE THREAD

**Issue by emtiu** [bit-team/backintime#1327]
The procedure is documented in #1042, but I'm not sure where best to publish: GitHub Wiki/FAQ, shipped docs, README.md?

@gsker Could you write a Howto compiled from the information in #1042?

**Comment by buhtz** [comment]
I wonder about the need of this. Maybe I misunderstand something.

CentOS is based on RedHead. They do have package management and a package repository specific to their distribution. So if there are distro specific special steps to do to install BIT this should be covered by how the package is created by CentOS community. It is their responsibility not ours. And there is no need for documentation on our site. No need to read a docu because the users just need to install the CentOS package of BIT.

If this is about install upstream BIT from our git repo: Also here the makefile should cover CentOS specific steps if there are some.

But maybe I miss something.

We have a developers/maintainer specific docu section in `common/doc-dev` based on markdown files.

**Comment by buhtz** [comment]
Closing this ticket based on the comment above.

CentOS do not exist anymore. Despite of that any distro-specific install documentation should live at the distros own support channels (e.g. a wiki) and their package management system; not at upstream.
