### ISSUE TITLE
Remove docbook elements

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1345]
Tag: Discussion, low
Time: relevant after (next) 1.3.3 release

In PR #1343 we become aware of docbook files in `qt/docbook/en`. I was looking into Wikipedia ([en](https://en.wikipedia.org/wiki/DocBook)/[ger](https://de.wikipedia.org/wiki/DocBook)), https://docbook.org/ and https://www.oasis-open.org/docbook/ about that.

It seems to be an (xml-based) markup language for documents like manuals, howtos, etc. A docbook can be converted into several publishing formats (e.g. PDF). So in my understanding it plays in the same league as restructeredtext and markup.

Looking deeper into the linked sources I would say that format is nearly dead. The two websites looking very old and not up-2-date. According to Wikipedia the latest standard 5.1 is from 2016.

Looking into our own commit history I see that Germar never modified the content of that files. I assume that Oprea Dan (the maintainer before Germar and founder of BIT) introduced that files before the repo moved to GitHub.

There is not much content in that files; nothing unique.

So I vote for removing the whole `qt/docbook` folder after the next release.

**Comment by emtiu** [comment]
We should check if any of those docs are processed/published somewhere, like on https://backintime.readthedocs.io/. If not, and they are truly as outdated as you found, then I agree to remove them.

**Comment by aryoda** [comment]
Here are all files containing the word `docbook` as potential candidates that must be changed when we remove docbook:

```
> grep -ri --exclude-dir=.git docbook
updateversion.sh:update_xml qt/docbook/en/index.docbook
qt/configure:addComment "docbook"
qt/configure:addInstallFiles "docbook/en/*.docbook" "/share/doc/qt/HTML/en/backintime"
qt/docbook/en/index.docbook:<!DOCTYPE article PUBLIC "-//OASIS//DTD DocBook XML V4.1.2//EN" "http://www.oasis-open.org/docbook/xml/4.1.2/docbookx.dtd" [
qt/Makefile:	#install docbook
qt/Makefile:	install --mode=644 docbook/en/index.docbook $(DEST)/share/doc/qt/HTML/en/backintime
qt/Makefile:	#uninstall files docbook
qt/Makefile:	rm -f $(DEST)/share/doc/qt/HTML/en/backintime/index.docbook
qt/Makefile:	#uninstall directory docbook
CHANGES:* GNOME: update docbook
CHANGES:* update man/docbook
CHANGES:* add English help (docbook)
```

**Comment by aryoda** [comment]
If required we could convert the docbook into markdown (result see below) with

```
pandoc -f docbook -t markdown index.docbook > index.md
```

The content of the docbook is quite simple and old, I think we can delete it

We have to modify at least `qt/configure` to remove the docbook installation (I do not even know how to view this installed docbook help ;-)

--------------------

Introduction {#backintime-introduction}
============

APP is a simple backup tool for Linux (this is KDE4 version). The backup
is done by taking snapshots of a specified set of folders.

All you have to do is:

-   configure where to save snapshots

-   cofigure what folders to backup

-   schedule automatic backup: disabled, every 5 minutes, every 10
    minutes, every hour, every day, every week, every month

APP acts as a \"user mode\" backup tool. This means that you can
backup/restore only folders you have write access to (actually you can
backup read-only folders, but you can\'t restore them).

If you want to run it as root you need to use \"sudo -i backintime\"
(command line) or \"backintime-qt\_polkit\" (GUI).

A new snapshot is created only if something changed since the last
snapshot (if any).

A snapshot contains all the files from the selected folders (except for
exclude patterns). In order to reduce disk space it use hard-links (if
possible) between snapshots for unchanged files. This way a file of
10MiB, unchanged for 10 snapshots, will use only 10Mb on the disk.

When you restore a file \'A\', if it already exists on the file system
it will be renamed to \'A.backup.currentdate\'.

This documentation is not maintained (at least for the moment), please
use the man-page \'man backintime\'

About APP {#backintime-about}
=========

APP was written by Oprea Dan (xxx), Bart de Koning
(xxx), Richard Bailey (xxxxx).

To report a bug or make a suggestion regarding this application or this
manual, sent a mail to <xxxxxx>.

This program is distributed under the terms of the GNU General Public
license version 2 as published by the Free Software Foundation. A copy
of this license can be found in the file LICENSE included with the
source code of this program.
