### ISSUE TITLE
Some translation work for French

### ISSUE THREAD

**Issue by jej** [bit-team/backintime#1391]
Hi,
Following the PR #1376 discussion, I did a review of the French translations. It was very clean globally.

My changes are here: https://translations.launchpad.net/backintime/trunk/+pots/back-in-time/fr/+filter?person=j3jc

Some points to be discussed (in the English source):
- "BackInTime" vs "Back In Time" or "Back in Time"?...
- "Préférences" is used in French (like "preferences" in English) but as I understand it's more concerning "Configuration" rather than settings as it says. I think it should be harmonized. "Configuration" for everything related to snapshots configuration, and "Préférences" for settings. But I think there is no "settings" pane in back in time for now, everything is in the "preferences" menu.
- "Copy links (dereference symbolic links)" is not clear. If I understand well, it should be "Copy link targets (dereference symbolic links)"
- "Copy unsafe links (works only with absolute links)": I don't understand well this concept of safe or unsafe links.
- Last log entry confuse me, because it shows the whole log anyway. I would prefer something like "Display log" even if last entries are shown by default.

Hope it helps,
J.

@buhtz @emtiu

**Comment by buhtz** [comment]
Dear @jej ,
thanks a lot for your work.

We will take a closer look at it and some discussion of course.

**Comment by buhtz** [comment]
Because we do prepare the next release between Christmas and new year I would suggest to carry most of that points in that Issue after that release.

> * "BackInTime" vs "Back In Time" or "Back in Time"?...

I would vote for "Back In Time" as the official name.
And as I can see so far it is what I can see at the most places in the GUI.

> * "Préférences" is used in French (like "preferences" in English) but as I understand it's more concerning "Configuration" rather than settings as it says. I think it should be harmonized. "Configuration" for everything related to snapshots configuration, and "Préférences" for settings. But I think there is no "settings" pane in back in time for now, everything is in the "preferences" menu.

Currently I can only find "Settings" in the GUI.
Reading in the web and looking for evidence about the difference of the terms preferences, settings, options I would like to document that sources
 - https://ux.stackexchange.com/q/17442/75302
 - https://ux.stackexchange.com/q/43040/75302
 - https://softwareengineering.stackexchange.com/q/338620/198281

In short:
 - The terms are nearly similar but have shades in there meaning.
 - There is no clear rule or decision about it.
 - One advice was to look into style guidelines (e.g. Gnome, Google Android Apps, ...).

As you pointed out currently the structure of the GUI needs a full redesign (or written new from scratch) before we can decide about such terms. I'm also not happy about the current structure.

> * "Copy links (dereference symbolic links)" is not clear. If I understand well, it should be "Copy link targets (dereference symbolic links)"
> * "Copy unsafe links (works only with absolute links)": I don't understand well this concept of safe or unsafe links.

This can be found in the _Expert Options_. I would put that onto the touch-that-later-when-redesign-the-gui-list. There are tooltips behind that two options pointing to the specific rsync argument.
Myself I don't understand that options well and would like to test them first before decide how to name them and describe them.

> * Last log entry confuse me, because it shows the whole log anyway. I would prefer something like "Display log" even if last entries are shown by default.

Do you mean the menu enry _View_ | _Last log_ ? I couldn't find _Last log entry_.

> @buhtz @emtiu

No need for that. ;) We monitor each activity on the repo.

**Comment by buhtz** [comment]
FYI: In preparation of a new release and based on Germar manual I will try to integrate the current state of translations from launchpad into our upstream repo here at Microsoft GitHub.

**Comment by buhtz** [comment]
Dear Jej,

our [Weblate translation platform](https://translate.codeberg.org/projects/backintime/common/) is no setup and updated to the latest state of Back In Time including ease some of the strings (PR #1448) to translate.

If you like it would be great if you could look into the French translations. Please let me also know if I should add you to the `TRANSLATIONS' file so you appear as a translator in the About dialog.

Kind
Christian

**Comment by jej** [comment]
Hi,

I did a first big review... For the details, maybe I will do more after I see the app running.

Yes you can add me in the credits (jej@github).

Thanks,
J.

**Comment by buhtz** [comment]
> Yes you can add me in the credits (jej@github).

Doing this via #1455

**Comment by buhtz** [comment]
Dear Jej,

did you got en automatic email in the last two days about you French translations on our translation platform?

I updated some strings so some need to be reviewed again. I just want to understand if the platform do mail translators automatically.
