### ISSUE TITLE
Update PPA for 22.04 to version 1.3.3 ?

### ISSUE THREAD

**Issue by speedy-10** [bit-team/backintime#1395]
Hi, it would be nice to get the newest bit-versions over the usual ppa, too:

https://launchpad.net/~bit-team/+archive/ubuntu/stable

Regards

**Comment by buhtz** [comment]
Dear @speedy-10 ,

I was informed that there is also a "testing" PPA. Maybe `ppa:bit-team/testing`?
BIT will hit the `stable` PPA some days or weeks later. There is no hard schedule.
Keep in mind that there is no guarantee that the PPA will always represent the current stable BIT version. It is recommended to use your GNU/Linux distributions own package repository as primary source. If they don't offer the current version open a bug report at the distros bug tracker. In that case you can also inform us about that ticket via the bit-dev mailinglist or via an Issue.

But you can [install](https://github.com/bit-team/backintime#installation) BIT also directly from git repo or from the source-tarball using `make`.

**Comment by buhtz** [comment]
Found it
https://launchpad.net/~bit-team/+archive/ubuntu/testing

**Comment by speedy-10** [comment]
thanks for your hints ans especially for keeping bit up-to-date!

**Comment by speedy-10** [comment]
Hi again, are there still some problematic bug reports, that prevent the publishing in the PPA?

**Comment by buhtz** [comment]
The next upcoming Ubuntu Version 23.04 ("Lunar Lobster") will have [backintime 1.3.3](https://packages.ubuntu.com/search?suite=lunar&searchon=names&keywords=backintime) because it does use Debians backintime package.

Germar will update the stable-PPA in the next days. He is the admin of that PPA.

From my point of view I would like to learn why someone would use a PPA? Is there a strict reason for this? Why not updating your Ubuntu? The latest "stable" Ubuntu does has BIT 1.3.2 on board.
Why not asking the Ubuntu folks for a backport of BIT to your 22.04? This is possible.

**Comment by Germar** [comment]
I pushed 1.3.3 to stable PPA some seconds ago.

**Comment by speedy-10** [comment]
thanks, it works for me.

**Comment by aryoda** [comment]
@speedy-10 Thanks for your confirmation!

Please note that other users reported an issue with our 1.3.3 Ubuntu PPA installation package that prevented BiT from starting: #1401 

The work-around (installation of the missing package) is described there...
