### ISSUE TITLE
backintime fails after upgrade to Fedora 37

### ISSUE THREAD

**Issue by tbclark3** [bit-team/backintime#1397]
A routine upgrade to Fedora 37 this morning included backintime 1.3.2 -> 1.3.3 and python3-qt5 5.15.6-9 -> 5.15.6-10. There was also a long list of upgraded qt5 packages.  Following the upgrade, the batch backup fails with:
```
Traceback (most recent call last):
  File "/usr/share/backintime/common/backintime.py", line 28, in <module>
    import config
  File "/usr/share/backintime/common/config.py", line 45, in <module>
    import tools
  File "/usr/share/backintime/common/tools.py", line 37, in <module>
    from packaging.version import Version
ModuleNotFoundError: No module named 'packaging'
```

The GUI also fails:
```
qt.qpa.xcb: could not connect to display localhost:10.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

/usr/sbin/backintime-qt-root: line 31: 162400 Aborted                 (core dumped) python3 -Es ${APP_PATH}/app.py "$@"

```

**Comment by buhtz** [comment]
Have you tried to install `packaging` module via `python3 -m pip install packaging`?

Because currently _Back In Time_ doesn't follow any packaging standards (e.g. `pyproject.toml`) it offers no automatic way to expose the dependencies. Please open a Ticket at Fedora about the missing dependency.

I assume this is Independent from the Qt/Wayland problem.

**Comment by tbclark3** [comment]
Thanks, but as far as I can tell there are no missing dependencies.  python3-packaging-21.3-6.fc37.noarch is already installed and hasn't changed.  I also think the QT/Wayland problem is independent.

**Comment by buhtz** [comment]
> python3-packaging-21.3-6.fc37.noarch is already installed

Mysterious. Do you use a special environment? A virtual environment, docker, etc?
Please post the output of `python3 -c "import packaging"` and tell us please in which folder do you executed it.
Do the same as root please.

Please show us the full output of `backintime-qt --diagnostics` and `backintime-qt-root --diagnostics`.

>    from packaging.version import Version
> ModuleNotFoundError: No module named 'packaging'

It is just a stupid shoot into the blue. Can you please add this line before line 37.

    import packaging

So in the end line 36 and 37 should look like this

    import packaging
    from packaging.version import Version

**Comment by aryoda** [comment]
> About the Qt-Wayland-Issue maybe @aryoda can tell something more.

I have put this issue on my TODO list (I need to set up a new Fedora 37 VM to check the reason for the Qt5 error message)...

**Comment by aryoda** [comment]
> Thanks, but as far as I can tell there are no missing dependencies. python3-packaging-21.3-6.fc37.noarch is already installed and hasn't changed. I also think the QT/Wayland problem is independent.

Do you know more details about the problems & possibly a solution?

We have exactly the same stack trace in issue #1401 so the package `packaging` is definitely the cause and cannot be found (or is incompatible)...

> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.

This may happen if you have booted into a console without a desktop environment (DE) or are installing via `ssh`.
Does one of these scenarios apply in your case?
Otherwise it could also be a DE that is not supported by Qt5. Which one are you using?

**Comment by aryoda** [comment]
@tbclark3 I have installed a Fedora 37 Workstation VM and need more info to reproduce this:

- Which desktop environment are you using?
- Do you use X11 or wayland?

**Edit:** You could install `neofetch` and attach the output here (+ the output of `echo $XDG_SESSION_TYPE`)
