### ISSUE TITLE
Excluding temp files

### ISSUE THREAD

**Issue by sspade1** [bit-team/backintime#1419]
It looks to be a basic feature, but I do not know to exclude a folder like `/home/sspade/.config/BraveSoftware/Brave-Browser/Greaselion/Temp`.
I tried to add the following exclusion rules:
```
/[Tt][Ee]?[Mm][Pp]/
/[Tt][Ee]?[Mm][Pp]/*
*[Tt][Ee]?[Mm][Pp]/*
/(?i)te?mp/
/(?i)te?mp/*
*(?i)te?mp/*
```
but the folder is still included in my backup.
What am I doing wrong ?
Should I use the advanced option to pass directly a parameter to rsync ?

**Comment by buhtz** [comment]
Dear @sspade1 ,
thanks for your Isssue.

This is not an easy topic and depends on rsync itself. I don't have a solution because I don't use that feature of rsync and also don't understand it. 😄 

If no one else has a good idea I would suggest to look into the StackOverflow & Co universe. If you can't find an answer there you should open your own question there. Would be great if you could link or post your solution here.

Further reading

- https://serverfault.com/q/801875
- https://stackoverflow.com/q/28439393/4865723
- https://manpages.debian.org/bullseye-backports/rsync/rsync.1.en.html#PATTERN_MATCHING_RULES
- https://manpages.debian.org/bullseye-backports/rsync/rsync.1.en.html#SIMPLE_INCLUDE/EXCLUDE_RULES

**Comment by buhtz** [comment]
You could try to test it with `rsync` itself using `--dry-run`. When using `--verbose` two time (`-vv`) you also get information about why a file was included or excluded.

    `rsync -vv --include '*1321*.jpg' --exclude '*132???.jpg' --dry-run . ..

[Source](https://debianforum.de/forum/viewtopic.php?p=1324192#p1324201)

**Comment by Germar** [comment]
Take a look at `man rsync` section `INCLUDE/EXCLUDE PATTERN RULES`. You can use `[Tt]emp` to exclude those folders or `[Tt]emp/*` to exclude everything inside that folder except the folder itself

**Comment by sspade1** [comment]
> Take a look at `man rsync` section `INCLUDE/EXCLUDE PATTERN RULES`. You can use `[Tt]emp` to exclude those folders or `[Tt]emp/*` to exclude everything inside that folder except the folder itself

Yes! It works.
I prefer [Tt]emp/* to be sure to not exclude any file or folder like "temperature".
Thanks
