### ISSUE TITLE
FileView can not open symlinked folders

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1476]
This issue needs further investigation. I won't touch it yet because I'm [in the middle of refactoring](https://github.com/buhtz/backintime/tree/feat/langmenu) `qt/app.py` while I uncovered this issue.

Reproduce:
 - Select "Now" in the timeline left to show the current state ot the filesystem and not any of the snapshots.
 - Double click on a folder which is a symlink.
 - Nothing will happen. The folder does not open.

The relevant code in the GUI is here:

https://github.com/bit-team/backintime/blob/1003d360d758bce78c6cd528ea41df3734fec95b/qt/app.py#L1338-L1353

In there the `self.sid.canOpenPath()` does return `False`.

It is not a serious bug. But I have the feeling that touching this will cause some more trouble and much more need to refactor. There might be a big workload hidden behind it. :smile:

**Comment by aryoda** [comment]
The idea is that symbolic links shall only be opened if the link points to a folder inside of the current snapshot:

https://github.com/bit-team/backintime/blob/2f7b6099edf40366da1c1020385b300ac2793080/common/snapshots.py#L2447-L2465

I have tested this by creating a symbolic link in the source folder and point to a sub folder within the source folder

```
source/data/
source/link_to_data/
```

**Edit: Stupid me, I had the "expert option" _Copy links (dereference symbolic links) activated so I have to retest all this...**

Test results:

1. After taking a snapshot the linked folder is contained as materialized folder (= **no longer a link**): It contains the same files as the originally linked folder (**as duplicated copies !!!**) 
The reason is that we use the `--copy-links` argument for `rsync` which transforms a symlink into the referent file/dir

2. The check in `canOpenPath()` if the link target is a folder within the snapshot is never used in this standard "browse backup" scenario.

3. If I manually create a symbolic link in the snapshot folder to a folder within the snapshot the link check does work correctly and the linked path is opened.

4. If I manually create a symbolic link in the snapshot folder to a folder **outside** the snapshot the link check does work correctly and the linked path is **not** opened.

5. In the `Now` "snapshot" (= source folder) a link is **never** opened because the variable `basePath` is wrong (contains `/backup`).

So to fix this we need to decide if we want to
a) follow each link in `Now` (no matter if it points inside or outside the source folder)
b) follow only links to target folder inside of `Now`
b) never follow links (current behavior)

Option b) is the easiest fix I think (by checking for the translated "Now"):

```
       if  self.isRoot or not os.path.islink(fullPath):  # should be the same as:  self.tag != _'Now'  # Snapshot ID's tag
            return True
```

BTW:
- `canOpenPath` should be renamed (refactored) to `IsPathInsideSnapshotFolder` or similar to make it more obvious what the function really does.
- `self.isRoot` is also a misnomer (means the backup source root folder displayed as "Now").
  It even collides with the meaning of `tools.py#isRoot()` (which checks if the current process is running with `root` user rights)
- The use of `--copy-links` should be mentioned in our FAQ as a reason for huge backups (if the backups source folder contains one or multiple links to target folder with large disk space consumption).
