### ISSUE TITLE
Could we possibly send issues or non-dev questions through a mailing list?

### ISSUE THREAD

**Issue by giteauserbit** [bit-team/backintime#1509]
Could we possibly send  questions issues through a mailing list rather than being nudged into using github?

I only found a mailing list for dev discussion (https://mail.python.org/mailman3/lists/bit-dev.python.org/).

**Comment by aryoda** [comment]
I do understand that you and maybe other users would prefer using a different platform but for historical reasons we are using Github and using a mailing list for issues instead (or "on top") would make our development workflows more complicated, difficult to follow and search. So for now we have no alternative for this I am afraid.

**Comment by buhtz** [comment]
Hello,
I understand your concerns against Microsoft GitHub. I can't speak for the whole team but I share your concerns. But as aryoda said we stay on GH currently because of historical reasons. Migration is on our todo list but with very low priority because of other rmore important issues.

The "bit-dev" mailing list is free for everyone. Feel free to ask or share what every you want even if it is not about "development".

Because of spam problems the admin of the mailing list server made account creation via the web interface mandatory. But you can work around this via sending an email with subject "subscribe" to bit-dev-join@python.org.

I updated the mailing list description to make clear it is open to every topic.

**Comment by giteauserbit** [comment]
Thank you both for your responses. Good to know it is on the list.

I will not hesitate to send my questions to the list next time -  thanks for updating the description of the list. 

I will close this issue.
