### ISSUE TITLE
Add PPA from @jean-christophe-manciot to the README

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1550]
Dear @jean-christophe-manciot,

would it be OK for you if we would add your PPA (https://git.sdxlive.com/PPA/about/) to the *Installation* section of our README file?

Please be aware of #1548 which is about removing the `debian` folder from this upstream repo.

**Comment by jean-christophe-manciot** [comment]
Of course.

**Comment by aryoda** [comment]
@buhtz I think we should then also remove (or better explicitly deprecate) our old Ubuntu PPA since it does not contain the most-recent version of BiT but is still used for installations, see eg. [this issue](https://github.com/bit-team/backintime/issues/1551#issuecomment-1763475095):

**Comment by buhtz** [comment]
> @buhtz I think we should then also remove (or better explicitly deprecate) our old Ubuntu PPA since it does not contain the most-recent version of BiT but is still used for installations, see eg. [this issue](https://github.com/bit-team/backintime/issues/1551#issuecomment-1763475095):

I would not be so "radical". It seems that Germar tries to keep it up to date no matter that it does not happen just in time.

My intention is to radical reduce the PPA section in our README. It should just link to the two known PPAs and state clearly that these are external resources we are not responsible for and that they might not be up to date. The PPA owners are responsible to add a README or something similar stating how to use (via apt install xzy) that PPA.

Here is a quick n dirty example

https://github.com/buhtz/backintime/blob/doc/1550ppa/README.md

**Comment by jean-christophe-manciot** [comment]
@buhtz 
Did you try to contact me directly through an email address ending with .jp regarding the PPA?

**Comment by buhtz** [comment]
> @buhtz
> Did you try to contact me directly through an email address ending
> with .jp regarding the PPA?

Yes, that is correct.

**Comment by jean-christophe-manciot** [comment]
@buhtz 
Do you mind if I answer your questions and concerns here? It would also allow others including @aryoda to chime in.

**Comment by buhtz** [comment]
Good idea.

**Comment by jean-christophe-manciot** [comment]
> I looked around in your docu (https://git.sdxlive.com/PPA/about/) but
> could not find a clear description about how to use a PPA to install
> BIT. In context of BIT I assume PPA users are rookies and not pros. At
> BIT upstream we currently do explain how to use Germars PPA:
> https://github.com/bit-team/backintime#alternative-installation-options
> But our goal is to reduce this README section as much as possible and
> just name the PPA and give a link to further install instructions
> provided by the PPA maintainer. Maybe you see a way to improve that
> situation?
> To my current understanding I would provide two URLs to my users in the
> BIT-upstream-README file:
>   - the PPA URL/name: https://git.sdxlive.com/PPA/plain/Ubuntu
>   - install instructions: https://git.sdxlive.com/PPA/about/#installing

The Ubuntu PPA is different from [launchpad PPAs](https://help.launchpad.net/Packaging/PPA) which are each focused on a single source package which is built by launchpad and hosted for many Ubuntu versions with a limited disk size; mine is focused only on the latest stable Ubuntu release, but tracks ~ 1k source packages resulting now in > 12k binary packages and the disk size is in theory unlimited but in practice limited by git performances (which are not optimal with binaries, especially with large packages). That's why I have chosen to build all those source packages for only the latest stable version of Ubuntu. As a side note, the latter has been recently upgraded to mantic 23.10, and all the latest versions of the tracked source packages will be soon be rebuilt and tested in that environment to replace all their "predecessors" in early November.

My suggestion is to specify the name of the package to install (backintime-qt) and the user will be able to follow the clear generic guidelines to install the PPA and **any** binary package.
I will try to add a few more lines to guide the "rookies".

> Your ubuntu folder is not generic but points to specific release
> (Lunar). In that case we have to update our readme.md everytime ubuntu
> comes up with a new release. Might it not be better to use something
> like "latest", "lts" or something else?

Each /etc/apt/sources.list points to a single Ubuntu distribution release which must match tha name of that folder. However, you can just point to the **latest stable Ubuntu release** without specifying its release name. Each Ubuntu user must know the name of his/her distribution to check if it is compatible with the PPA as described in the [PPA requirements](https://git.sdxlive.com/PPA/about/#requirements).

As a summary, I would recommend the following references on your side:

**PPA for the latest stable Ubuntu release**:
- [PPA distributing the latest stable release of backintime](https://git.sdxlive.com/PPA/about/)
- [PPA requirements](https://git.sdxlive.com/PPA/about/#requirements)
- [Installing the PPA and backintime-qt](https://git.sdxlive.com/PPA/about/#installing)

> I also found Debian packages related to bookworm. Here is the same
> problem. Additionally there is a "stable" and "unstable" folder inside
> the bookworm folder. How can this be real? Bookworm can not be both. It
> is unstable or stable.

Unfortunately, as already indicated in the [DR contents](https://git.sdxlive.com/DR/about/#dr-contents), this specific repository will soon be removed due mainly to a lack of time to feed it (among other reasons).

"stable"/"unstable" refers to the source packages, not the whole distribution.
Also, opinions vary greatly to distinguish stable from unstable.
Mine is straightforward: the responsibility relies only upon how the developers tag the source upstream repository.
- source packages are considered **stable** when the tag does not contain the following sub-strings: *alpha*|*ALPHA*|*beta*|*BETA*|*dev*|*DEV*|*exp*|*EXP*|*~git*|*GIT*|*pre*|*PRE*|*rc*|*RC*|*test*|*TEST*
- source packages are considered **unstable** when the tag contains the aforementionned sub-strings or when there is no tag at the specific chosen checkout

> Currently BIT-upstream do provide a "debian" folder. This folder is used
> by yourself and also by another PPA (at Launchpad by Germar Reitze). In
> the near future we will remove that folder from our upstream repo
> because it is distro specific. So I recommend you to store it elsewhere.
> We do expect that Germar will move it to another GitHub or Launchpad
> repo. But it is not decided yet. As an alternative you might use the
> official Debian package source at Salsa.

Don't worry about it. I've already made the modifications to take into account your move. I've planned to use the debian folder from the official Debian package source at Salsa, which will have some impact on the packaging: the number of binaries will be different; only backintime-common and backintime-qt remain which is not a problem since all other binaries are virtual packages.
If you want, I can make a pre-run by building the latest bit release with the new debian folder to show you how it will look like.
