### ISSUE TITLE
Option to set niceness

### ISSUE THREAD

**Issue by noyannus** [bit-team/backintime#1584]
BiT rsync processes can consume a high amount of cpu load.

This may impede other speed critical tasks. Also, the machine becomes hot.

Please include in the preferences an option to set niceness, e.g. with a numeric stepper. 

This option is of enough weight that it has been suggested as early as #59.

**Comment by emtiu** [comment]
Back In Time allows `nice` and `ionice` to be used for its `rsync` processes in the **"Expert Options"** tab of the profile settings. What exactly do you think should be changed about those settings?

**Comment by buhtz** [comment]
See also the man page that two options.
https://manpages.debian.org/testing/backintime-common/backintime-config.1.en.html#profile_N_.snapshots.cron.ionice

**Comment by noyannus** [comment]
> What exactly do you think should be changed about those settings?

IMHO, they could appear at a more prominent place, to be obvious for the less technical inclined user. (I imagine a GUI accustomed Apple refugee on Linux Mint. :-) ) That would bring BiT a small step ahead in GUI convenience.

The General tab uses a very broad pull-down menu for Mode: That could be narrowed to make room for, e.g. "Resource hunger [NN]" (combination settings for nice and ionice), or, more detailed, "CPU hunger [NN]" and "I/O hunger [NN]". "Hunger", to be understandable for the layman; the nice/ionice background would then be explained in the Help and/or FAQ.

**Comment by buhtz** [comment]
I agree that the settings dialog and the rest of the GUI need a big redesign.

My opinion is that such options need to be in an "expert" section or much better hidden behind a "advance options view". Regular users should not think about ionice and nice at all.
BIT is not an "expert application", it is the opposite.
But it is open by design. So if there are expert users they can manipulate the crontab or a manual backintime call themselfs.

**Comment by noyannus** [comment]
> My opinion is that such options need to be in an "expert" section or much better hidden behind a "advance options view". Regular users should not think about ionice and nice at all.

Fine for me. But there is a middle ground; users could control nice/ionice in a simplified way, to make it more accessible. "CPU hunger" is immediately understood, "ionice" less so.

**Comment by buhtz** [comment]
Yes I see your point and I think we do agree.

I would vote to close the Issue because its initial problem do not exists. The secondary topic about redesigning the UI is to meta to having it in an Issue. It is on our list as a very big topic. I would like to think about the redesign at once before touching any code.

Before doing this we need to close #1575 and improve the test suite.

**Comment by noyannus** [comment]
I agree there are more pressing concerns. Closing.
