### ISSUE TITLE
"Backup folders" list should reflect the selected snapshot

### ISSUE THREAD

**Issue by buhtz** [bit-team/backintime#1585]
# Problem description
![grafik](https://github.com/bit-team/backintime/assets/11861496/9441c28e-c2db-4368-a85f-76b76ee4bd91)

Look on the right column with four folders. One of them is named `tab-cloud`.
Look in the middle column at "Backup folders". The `tab-cloud` is missing in that list.

The `tab-cloud` was included in the past. But I removed it from the Include list.

The problem is that "Backup folders" do reflect the current state of the  Include list. But it should reflect the Include list at that point the snapshot was made.

# How should it be
Regarded to the screenshot the folder `tab-cloud` should appear in the middle column ("Backup folders") because it exists in the snapshot. It does not matter that it does not exist in the real filesystem anymore.

# What need to be done
Technically it is not complex or hard to understand but for beginning contributors this is an Issue causing a lot of work. First of all the code need be investigated. Please describe a possible approach before writing to much code.

**Comment by emtiu** [comment]
Actually, I think this is rather important. It might lead users to think that they have lost data, because a folder that was included in the backup is not displayed.

In general, backintime is not great at handling Profiles with frequent changes to the Include/Exclude list. I think this should receive attention.
