### ISSUE TITLE
Settings conversion dialog after upgrade is misleading

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#162]
After upgrading from BiT 0.9.26 to a testing version (0.9.99.32), BiT said it would convert the settings to a new format. The conversion went ok, but the dialog afterwards was a bit misleading. It had an error cross and the title was "Error - Back In Time". The text itself was fine, though.

See the attached picture for an illustration.

---

Imported from Launchpad using lp2gh.
- date created: 2010-04-16T15:01:17Z
- owner: lysias
- the launchpad url was https://bugs.launchpad.net/bugs/564747

**Comment by Germar** [comment]
(by lysias)

**Comment by Germar** [comment]
(by danleweb)
The message box type is wrong (if should be an information not an error). The message show that everything was ok.

**Comment by buhtz** [comment]
The initial issue description is a bit misleading. That is the dialog (taken from launchpad ticket):

![image](https://github.com/bit-team/backintime/assets/11861496/3e9c452d-74d4-45d0-a5cb-d11be01a8135)

I couldn't find any of that strings in the current sources via `git grep`. I assume it was removed because conversion from 0.9.26 is not relevant today anymore.

I checked older commits. In [Nov 2009 Bar de Konig](https://github.com/bit-team/backintime/blob/b94d003c354db0353e93594c7185eaaeb18cced8/common/config.py#L594) introduced that error message. Compared to `dev` it is removed today.
