### ISSUE TITLE
No execution log

### ISSUE THREAD

**Issue by ceperman** [bit-team/backintime#1643]
I think an overall execution log is needed, one that logs when BackInTime runs and what actions it takes or doesn't take. If there is one currently I've not found it.

For example, I look at my snapshots and don't see all that I expect - there is only one for this month and I expect to see more. I don't know if this is because (1) the schedule didn't call for them to be taken, (2) smart remove or some other action has removed them, (3) BackInTime didn't execute at all. or some other reason. At the moment I'm in the dark about what's happened.

**Comment by buhtz** [comment]
Dear ceperman,
thanks for your report.

We have [a section about logging and lock files](https://github.com/bit-team/backintime/blob/dev/common/doc-dev/4_Control_files_usage_(locks_flocks_logs_and_others).md) in our developers documention. It is an ongoing investigation because the current maintenance are not the founders of BIT. But you won't find much in there about log files.

So I started to create two FAQ entries about log files. Please see my PR #1644 and feel free to review it and suggest improvements. There are the two new FAQ entries: [Where is the log file?](https://github.com/buhtz/backintime/blob/doc/1643faq_about_logs/FAQ.md#where-is-the-log-file) and [How to read log entries?](https://github.com/buhtz/backintime/blob/doc/1643faq_about_logs/FAQ.md#how-to-read-log-entries).

Would this information help you to answer your questions?

We are aware that there is room for improvement. Currently we do not have an active discussion or decisions about further development.

Back to your question I assume you refer to something that could be named as an "application log"? BIT do use syslog for its application log. This means you have to check your syslog or systemd-journal. See the new FAQ entries I linked to about how to read syslog entries.
