### ISSUE TITLE
`msgfmt` not found during `make install`

### ISSUE THREAD

**Issue by lcubelongren** [bit-team/backintime#1661]
Opened by accident, please delete. Sorry!

**Comment by lcubelongren** [comment]
Was looking at opening an Issue over the dependencies while building and installing via make.
Here's where I ran into a problem:

`~/backintime/common$ ./configure && make`
Replacement of python path with "/usr/bin/python3" successful.
All OK. Now run:
    make
    sudo make install
msgfmt -o po/zh_TW.mo po/zh_TW.po
make: msgfmt: No such file or directory
make: *** [Makefile:100: po/zh_TW.mo] Error 127

Which was fixed by installing gettext and running the above command again.

Is msgmt covered by one of the dependencies already listed in the docs?

**Comment by aryoda** [comment]
> Is msgmt covered by one of the dependencies already listed in the docs?

The (Debian) package that contains `msgfmt` (`gettext`) is mentioned in our "how to build" doc:

https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#dependencies

```
> dpkg -S msgfmt
libicu-dev:amd64: /usr/include/unicode/msgfmt.h
gettext: /usr/share/man/man1/msgfmt.1.gz
gettext: /usr/bin/msgfmt
```

We could also mention `msgfmt` there but I would refrain from that because then we had to mention all other used binaries from other dependent packages...

**Comment by lcubelongren** [comment]
Ah, I missed that. Thanks for clearing that up for me!
