### ISSUE TITLE
Update PPA

### ISSUE THREAD

**Issue by speedy-10** [bit-team/backintime#1670]
Please update the PPA:
 @Germar](https://github.com/germar)'s Personal Package Archive 
[ppa:bit-team/stable](https://launchpad.net/~bit-team/+archive/ubuntu/stable)
for a newer version.

Regards

**Comment by buhtz** [comment]
Dear speedy-10,
thanks for your request.

As an alternative have you tried the second PPA?
"[jean-christophe-manciot](https://github.com/jean-christophe-manciot)'s PPA distributing [Back In Time for the latest stable Ubuntu release](https://git.sdxlive.com/PPA/about). See [PPA requirements](https://git.sdxlive.com/PPA/about/#requirements) and [install instructions](https://git.sdxlive.com/PPA/about/#installing-the-ppa)."

Please note that the maintenance team itself is not responsible for any 3rd party source. A PPA is such a source no matter that one of our team members manage one of it.

For Back In Time upstream I close this Issue because it is not relevant and we can not do anything about it. Germar will receive your message because you used his name with the @ sign. But it is hard to reach him even for ourself. You can try to conact him via [Launchpad](https://launchpad.net/~bit-team/+archive/ubuntu/stable) but I assume that this messages will be redirected into the same mail box.

Feel free to ask further questions or re-open the Issue.

Christian

*EDIT*: You can [install BIT from upstream](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#build--install) also. Please ask back if you need assistance. To stay up-2-date if a new release comes out you can subscribe to the [releases feed](https://github.com/bit-team/backintime/releases.atom) or to [our mailing list](https://mail.python.org/mailman3/lists/bit-dev.python.org/).

**Comment by speedy-10** [comment]
I read his description "[jean-christophe-manciot](https://github.com/jean-christophe-manciot)'s PPA distributing [Back In Time for the latest stable Ubuntu release](https://git.sdxlive.com/PPA/about)":
"This PPA is operational for the non-LTS Ubuntu distribution mantic (23.10) only."
So I didn't try it with LinuxMint 21.3.

**Comment by buhtz** [comment]
Your Mint version is based on Ubuntu 22.04. Give that PPA a try.
Or download the deb files from Debian:
- https://packages.debian.org/sid/all/backintime-common/download
- https://packages.debian.org/sid/all/backintime-qt/download

I don't know the update policy of Mint. But in the end you could contact your distros package maintainer.
