### ISSUE TITLE
Restore (with exclusion)

### ISSUE THREAD

**Issue by coffseducation** [bit-team/backintime#1727]
Hello,

I need to restore my system after an upgrade fail.
I have a main drive with home folder then another drive with Music & Videos that have a bind mount.
I have a third drive installed that has BiT backups. I have backed up both drives.

I want to re-install. How can I do so without re-installing the data for the 2nd drive.
(Yes, I should have created two profiles/jobs).

In fact I cannot find any clear instructions on restore at all - let alone with exclusion of directories.
Excluding directories is clear with backups, but not with restore.

Should I use Lucky Backup for this procedure?

Thanks.

**Comment by buhtz** [comment]
Hello coffseduction,

Thank you for taking the time to report the issue and providing the details. We appreciate your feedback.

Please post the output of `backintime --diagnostics` or give us your version of Back In Time if that command is not available in your version.

I have problems to understand your use case. You fresh installed your whole system (which OS?). And now you want to restore some files and folders from a previous backup you have done with Back In Time. Am I right so far?
I did not understand what you mean by "install" or "re-install" in the context of Back In Time. I also not sure what it is about all the drives involved.

The docu about it needs improvement, you are right.

If you just want to use your files and folders from your backup then just do it. You don't need the restore feature in Back In Time for this. The backup is just a bunch of folders and files. Copy them with your file manager where every you want them.

If you want to use the restore feature of Back In Time you just do it, too. Have you setup Back In Time on your new system so that it shows you the backups?

Best regards,

**Comment by coffseducation** [comment]
Thank you so much for the reply! 

re: backintime --diagnostics. After logging in at sddm on Kubuntu the screen freezes so I cannot get the version of BiT. The upgrade to Noble Numbut failed. I can switch to a tty so I will get that if it is important. I will get back to you.

No fresh install - yet. I have only used a live environment of the Garuda iso to try to understand the BiT process before committing further. BiT complains about the backup location not existing, but perhaps I need to install for it to work properly? I am unclear on the process here.

re: And now you want to restore some files and folders
- I want to install my /home directory - excluding Music & Videos. My home directory includes bind mounts to another drive with Music & Videos, so there is not need to reinstall those (just remount), nor will all that data fit on the main drive anyway if that is where it would try to go.
I mention this as the only option for restore I have seen is to select the snapshot (and all that is within it -no exclusion).

If you just want to use your files and folders from your backup then just do it. You don't need the restore feature in Back In Time for this.
- Yes, thanks for the clarification. Last time I had an issue I use Lucky Backup to restore as I could not understand how to use BiT. I feel I am doing a dis-service to BiT by not using it for restore though!  Have you setup Back In Time on your new system so that it shows you the backups?
-I feel I am missing something simple and BiT knows how to do everything I should need. Apologies. 

Thanks!

**Comment by coffseducation** [comment]
Back In Time version 1.4.3 on Kubuntu 23.10

**Comment by coffseducation** [comment]
Ok, I could not get BiT to see any config file. Dolphin showed them, but BiT could not see them in the directory.
I am restoring with Lucky Backup.
I suppose that means I will have to delete the backups in order to make room for a new BiT profile.
Thanks for the help.
Closing.

**Comment by coffseducation** [comment]
SOLVED!


Ugh! I finally figured it out!

When the system is re-installed the BiT drive needs taking ownership of again!!

I could restore the files with Lucky Backup so did not even consider this before.

After owning the drive the config imported and populated the backup list!

**Comment by buhtz** [comment]
Thanks for your feedback. Happy to hear that it went well on your side.

We will work on the documentation about the topic.
