### ISSUE TITLE
exclusion list

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#175]
Please add exclusion entries for firefox cache files to the default exclusion list:
/home/_/.mozilla/firefox/_.default/Cache
/home/_/.mozilla/firefox/_.default/OfflineCache

I intentionally included /home/ because it should also work when BiT does a system backup as root.
The ~/ pattern points only to one path (in this case /root).

Actually there are different types of files to exclude. Some files can be excluded from backup altogether (cache files, thumbnails etc.), others should be excludeable from older snapshots but the file should still always be present in the backup (the last snapshot). Files of the latter type include repository files of versioning systems (cvs,svn,bazaar,...) and some databases.

*,v for example should catch rcs files that should be in the backup, but not in every different version.

Other exclusion entries that could be available as preconfigured entries, but deactivated by default:
/home/_/.VirtualBox/HardDisks
/home/_/.VirtualBox/Machines/_/Logs
/home/_/.VirtualBox/Machines/*/Snapshots

This is deja-dup's build-in exclude list:
~/.cache
~/.thumbnails
~/.gvfs
~/.xsession-errors
~/.recently-used.xbel
~/.recent-applications.xbel
~/.Private
/proc
/tmp
/sys

---

Imported from Launchpad using lp2gh.
- date created: 2010-12-19T22:37:14Z
- owner: ceg
- the launchpad url was https://bugs.launchpad.net/bugs/692359

**Comment by Germar** [comment]
(by danleweb)
I can add firefox cache by default but you can always add them manually. Everyone has it's own needs.
I don't agree about VirtualBox harddisks. Some peoples may want to backup them.

Regards,
Dan

**Comment by Germar** [comment]
(by ceg)
Hi,
you're right, the VirtualBox paths should probably not be active by default. I have added the rules manually, and wanted to post them so they can be added/documented with the default list. Maybe, if activating/deactivating rules where possible, paths like those for VitrualBox could be shipped but be deactivated by default, while the cache paths can be shiped active.

**Comment by Germar** [comment]
(by ceg)
In fact, I'd like to have backups of large files like the virtual box images, just not all old versions from it.

We'd need an "exclude from snapshotting" (aka nocow, no copy on wirte) list.

**Comment by DecoDogs** [comment]
I'm tacking onto this issue since it's already open, though my request is a bit different.  Punt it out if you wish.

There are occasions when quite a number of 'excluded' files and folders need to be added.  It's pretty laborious to add via the BIT I/F, so I directly edit the config file (yes, I'm aware of the dangers).  The issue arose for me when I decided that it would be useful to keep an occasional snapshot of /etc.  I really want to only capture those things readable by a regular user, so don't especially want to run BIT as root.

First, while not a big deal, I note that the sorting order for excluded entities in the config file follows this pattern:

profile7.snapshots.exclude.1.value=.gvfs
profile7.snapshots.exclude.10.value=/proc/*
profile7.snapshots.exclude.11.value=/sys/*
profile7.snapshots.exclude.12.value=/dev/*
...
profile7.snapshots.exclude.18.value=/etc/mtab.fuselock
profile7.snapshots.exclude.19.value=/etc/shadow
profile7.snapshots.exclude.2.value=.cache*
profile7.snapshots.exclude.20.value=/etc/shadow-
profile7.snapshots.exclude.21.value=/etc/subgid-
...

rather than strict sequential sorting.  One suggestion is to sort in the expected, i.e., 1, 2, 3, ... 9, 10, 11, ... 19, 20, 21... order (or make everything a 4, 5, 6...? digit value).

Alternatively, and to keep meddlers such as myself from editing the config files directly, provide an easier way to select excluded files/folders.

Ultra low priority.

Ed

**Comment by Germar** [comment]
Multi selection for in-/exclude has been added in `1.0.28` which should make it easier to add a bunch of files.

I changed the sort order to numerical instead of alphabetical.

Ups, overseen the ultra low priority :grin: :wink:

**Comment by DecoDogs** [comment]
Well, ultra fast response!  Thanks.  I did not realize that multi selection worked.  Duh.  Consider head slapped.

**Comment by buhtz** [comment]
I would be carefull with excluding things by default. When you exclude Firefox cache you should take other browser caches into acount, too. This is to much work and not the responsibility of BIT. It is the users responsibility.

On the other (more important) hand: Somebody need the cache. I won't exclude it from my backups. It is a very special need I think.

I would recommand to close this Issue. @Germar ?

**Comment by emtiu** [comment]
I agree that we can close this Issue. When another well-founded request to change the default excludes comes around, it can go into a new Issue.
