### ISSUE TITLE
Update documentation "Expert Options"

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#182]
I suggest to update the documentation page at http://backintime.le-web.org/documentation/settings-dialog/ 
By adding some information about the following two options:
- "Copy unsafe links (works only with absolute links)"
- "Copy links (deference symbolic links)"

This is related to https://bugs.launchpad.net/backintime/+bug/706656

---

Imported from Launchpad using lp2gh.
- date created: 2014-06-29T18:06:35Z
- owner: francewhoa
- the launchpad url was https://bugs.launchpad.net/bugs/1335654

**Comment by Germar** [comment]
(by francewhoa)

**Comment by Germar** [comment]
(by germar)
Ahmm, that documentation does already smell like a dead rabbit... It didn't got any updates for ages.

**Comment by buhtz** [comment]
Issue is fixed long time ago (January 2015) related to Issue #347.

The "documentation" was added as ToolTips inside the GUI. I like self describing GUIs. ❤️ 

Of course the "quality" is discuss able because the ToolTips are just snippeds from the rsync manpage. But the quality of our end user docu is a meta topic not related only to this Issue here.

I also still think about how BIT and the BIT-team should deal with rsync related support questions.
