### ISSUE TITLE
Failing test on Ubuntu 24.04 about PyFakeFS version (was: BIT 1.5.3 make test fail)

### ISSUE THREAD

**Issue by Truck5067** [bit-team/backintime#1934]
I am attempting to install backintime 1.5,3 (I have been using version 1.4.3 - that has become very slow).

Ubuntu 24.04 upgrade from 22.04

I had to force the install of pylint 3.3.0  with pip install --force pylint==3.3.0 --break-system-packages

I cloned the git file then ./configure&& make

Then did a make test

I am getting the error below

I am willing to test any patches.

Thanks
Stephen Carr

FAIL: test_001_depency_workaround (test.test_uniquenessset.General.test_001_depency_workaround)
Workaround until #1575 is fixed.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sgcarr/Downloads/backintime/common/test/test_uniquenessset.py", line 65, in test_001_depency_workaround
    self.assertTrue(pyfakefs_version >= min_required_version)
AssertionError: False is not true

**Comment by buhtz** [comment]
Hello Truck,

Thank you for taking the time to report the bug and providing the details. I appreciate your feedback.

I will improve the verbosity of the error message, so next time it is clear to the a user what is wrong.
Because you are using Python 3.12 (or later) you need to upgrade "pyfakefs" to minimum version 5.7.0.

Anyway. If your BIT is slow I am assuming that the latest version of BIT want change that.

If you have any more details to share, feel free to reach out.

Not sure when we'll find the time to work on it. Please see the projects background information to get an idea about our workflow and priorities:

- [Maintenance status](https://github.com/bit-team/backintime#maintenance-status)
- [The team](https://github.com/bit-team/backintime#the-team)
- [Strategy outline / Roadmap](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#strategy-outline)

Best regards,
Christian
