### ISSUE TITLE
GUI does not scale when monitor is 4k

### ISSUE THREAD

**Issue by thereticle** [bit-team/backintime#1946]
Having changed my monitor from Full HD to 4k, now the GUI is very small. 
I have already changed all the system settings to adapt the Xfce4 environment but this GUI does not scale.
What can I do?

O.S.: Xubuntu 24.10

**Comment by buhtz** [comment]
Hello thereticle,

Thank you for taking the time to report the bug and providing the details. I appreciate your feedback, will investigate the issue, and work on a solution to the best of my ability.

Your issue is the prefect opportunity to improve our documentation. We had similar issues in the past. But without a 4k monitor on my own I am not able to reproduce the issue and document the steps to solve it.

For me it was never clear what the problem is or how to solve it. I hope you can bring in some light.

Please provide the output of `backintime --diagnotics`.

Have a look at [this comment about `qt5ct`](https://github.com/bit-team/backintime/issues/1428#issuecomment-1627767290), but use `qt6ct` please because BIT does use Qt6.

Please try to remember and document the steps you have done, so we can add this to our documentation.

If you have any more details to share, feel free to reach out.

Please see the projects background information to get an idea about our workflow and priorities:

- [Maintenance status](https://github.com/bit-team/backintime#maintenance-status)
- [The team](https://github.com/bit-team/backintime#the-team)
- [Strategy outline / Roadmap](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#strategy-outline)

Best regards,
Christian

**Comment by thereticle** [comment]
Hi  buhtz,

Well, I’m not very experienced.  
As I mentioned, I recently purchased a 4K monitor, and when I started Xubuntu 24.10, everything looked incredibly tiny.

I managed to enlarge the windows and the window fonts by doing the following:  
1. Settings → Appearance → Settings Tab → Window Scaling → 2x  
2. Settings → Window Manager → Theme → default-xhdpi  

This fixed the whole Xfce4 environment, but not all programs resize their GUIs.  

So, I looked for information on some of the programs I use.  

For example, the developer of Shotcut, a video editing program I use, suggested launching the program by adding the parameter `QT_SCALE_FACTOR 2` after the program’s name like this:  

`user@user-PC:~$ shotcut --QT_SCALE_FACTOR 2`

and it worked.  

Then I tried the same with Back in Time, but it didn’t work. So, I read this interesting article https://doc.qt.io/qt-5/highdpi.html  and  asked Bing Copilot how to start a program with that parameter set to 2.  
Copilot suggested using the `env` command to set the environment before running the application.  

So, I modified the command to:  

`user@user-PC:~$ env QT_SCALE_FACTOR=2 backintime-qt`

and it worked!  

So, for me, the problem is solved. Now it’s up to you to modify the program so that the adjustment happens automatically, perhaps by setting the variable `QT_AUTO_SCREEN_SCALE_FACTOR` to 1 as mentioned in the article.  

I think I can mark this bug as solved.

I hope I’ve been helpful.  
Cheers!

**Comment by buhtz** [comment]
Do I understand it correct that BIT wasn't the only application on your system with scaling problems?

Note to myself: https://debianforum.de/forum/viewtopic.php?t=191045

**Comment by thereticle** [comment]
Yes, I can confirm that Back In Time is not the only application whose GUI doesn’t scale properly on a 4K monitor.

At the moment, I’ve used the method described above with: Back In Time, Qbittorrent, Epson Scan 2, Audacity, HPLIP Toolbox, HPLIP Fax Utility, and HPLIP Address Book.  

I also tried with GIMP, but it doesn’t work. From what I’ve read here and there, it seems it won’t work because the stable version of GIMP, 2.10.38, is based on GTK 2. However, version 3, which is still in beta, does work. I installed it by following the instructions on this page: [https://www.gimp.org/downloads/devel/](https://www.gimp.org/downloads/devel/).  

**IMPORTANT**  
In any case, I just discovered that you can set this option globally by adding a line with `QT_SCALE_FACTOR=2` at the end of the file `/etc/environment`.  
I am not sure, however, that it works with **ALL** applications that do not scale the GUI.

**Comment by buhtz** [comment]
I will add an entry about it in our FAQ.
But BIT itself won't handle that or ask for the resolution of the users monitor. This is IMHO out of the scope of a backup application.
