### ISSUE TITLE
[Question] Backup Docker volume

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#1948]
I have some docker volume on my laptop, can I use backintime to backup `/var/lib/docker/volumes`?

**Comment by buhtz** [comment]
Hello lamyergeier,

Thank you for taking the time to ask.

> I have some docker volume on my laptop, can I use backintime to backup `/var/lib/docker/volumes`?

Why not? If this are just files in the file system it should work. I don't see a reason why it should not. But I am not experienced with Docker.

Let us know if it worked for you.

Regards,
Christian

**Comment by buhtz** [comment]
Hello lamyergeier,
is this issue still relevant for you? I need some feedback and response from you. Otherwise I am not able to help you and need to close the issue.

Regards,
Christian

**Comment by STPKITT** [comment]
Hi,
AFAIK it is necessary to shutdown the running docker containers in order to back them up properly, otherwise running databases etc. could be in an "unclean" state. So I wonder if backtintime could implement an option where the user can set a checkmark so that backintime would automaticall shutdown all running docker container or therefor every running container formats prior to backing up, then do the backup and after finishing automatically restarting the containers it shut down before.
I typed this here in order not to spam the issue tracker, but I'd say it's worth a new feature request issue. What do you think @buhtz ?

**Comment by buhtz** [comment]
Hello STPKITT,
thank you for your comment and thoughts on that topic. I appreciate that.

> I wonder if backtintime could implement an option where the user can set a checkmark so that backintime would automaticall shutdown all running docker container ...

Technically it might be not difficult to implement that. But it is IMHO a special case for a specific user group. I don't say it is a rare use case. But the primary targeted user group for BIT are desktop end users. Those usually do not use docker.

But BIT does offer the [user-callback system](https://backintime.readthedocs.io/en/latest/user-callback.html) or the pluginsystem (not documented) to solve such special cases very easy.

Might this be an option?

> I typed this here in order not to spam the issue tracker, but I'd say it's worth a new feature request issue.

Yep, this is OK.

Regards,
Christian

EDIT: Maybe we should add FAQ entry about that? And maybe BIT can give a warning/hint when a docker volume is added to the _Incluce_ list. What do you think?
