### ISSUE TITLE
Address TODO in backintime/common /password_ipc.py for error handling

### ISSUE THREAD

**Issue by DeependraChaddha** [bit-team/backintime#1971]
I noticed 3 TODO tasks in password_ipc.py, all 3 related to exception handling. Is it okay if I address those tasks? 
Just have to handle FileNotFoundError in one of them and write to stderr in the other two.

**Comment by buhtz** [comment]
Hello Deependra Chaddha,

Thank you for taking the time to report. I appreciate your feedback.

You can directly link/reference code in an issue like this:

https://github.com/bit-team/backintime/blob/b9dbc30c6c02a582bf19325b87e081f53618ab31/common/password_ipc.py#L31-L37

https://github.com/bit-team/backintime/blob/b9dbc30c6c02a582bf19325b87e081f53618ab31/common/password_ipc.py#L54-L61

https://github.com/bit-team/backintime/blob/b9dbc30c6c02a582bf19325b87e081f53618ab31/common/password_ipc.py#L80-L86

This TODO's are more complex than you might think. And they do have implications to other aspects of BIT and its behavior. Before you start anything please pick one and explain how you would address them.

Please keep on important thing in mind: AI-generated content is strictly prohibited. Accounts submitting such material will be reported for abuse to Microsoft GitHub.

Please see the projects background information to get an idea about our workflow and priorities:

- [Maintenance status](https://github.com/bit-team/backintime#maintenance-status)
- [The team](https://github.com/bit-team/backintime#the-team)
- [Strategy outline / Roadmap](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#strategy-outline)

Best regards,
Christian

**Comment by DeependraChaddha** [comment]
Thanks for your reply, for the first TODO in [backintime/common/password_ipc.py](https://github.com/bit-team/backintime/blob/b9dbc30c6c02a582bf19325b87e081f53618ab31/common/password_ipc.py#L31-L37) 
 I was thinking of editing as follows:  
Original: 
```def delfifo(self): 
     """Remove named pipe file.""" 
     try: 
         os.remove(self.fifo) 
     # TODO: Catch FileNotFoundError only 
     except: 
         pass 
```
Final: 
```def delfifo(self): 
     """Remove named pipe file.""" 
     try: 
         os.remove(self.fifo) 
         except FileNotFoundError:
           logger.error(f'File Not Found')
         except:
           pass
``` 
The places where this function was being called in BIT were in the following functions: https://github.com/bit-team/backintime/blob/b9dbc30c6c02a582bf19325b87e081f53618ab31/common/password.py#L56-L114 
and
https://github.com/bit-team/backintime/blob/b9dbc30c6c02a582bf19325b87e081f53618ab31/common/password.py#L156-L159
As the edit does not change the functionality of delfifo method, it seemed to me it will not affect the working of other functions.  
Maybe I should only focus on one task in one issue. So if this solution is satisfactory for you, I can try to work on other TODO's in a different issue, otherwise I won't try to make any changes.

**Comment by buhtz** [comment]
Sorry. I appreciate your efforts but I would suggest you look for another issue.

The second (and to broad!) `except` need to be removed:

     """Remove named pipe file.""" 
     try: 
         os.remove(self.fifo) 
         except FileNotFoundError:
           logger.error(f'File Not Found')


Now you have the situation that only filenotfounderrors are handled and the rest results in a real exception when BIT runs.

The key question is: Do we know if and which other exceptions might occur?

The next step would be to do systematic manual tests of all possible use cases where this part of the code is invovled and see how BIT reacts if there might be exceptions different from filenotfounderror we currently do not know about. This is a lot of work. That is why I set a TODO comment only because I knew it is to much for work now.

I can not accept a PR like this without heavy testing. And as you might have noticed our unit test coverage is low and can not be trusted. See [Strategy outline / Roadmap](https://github.com/bit-team/backintime/blob/dev/CONTRIBUTING.md#strategy-outline) for details about the problems we need to tackle down.

**Comment by DeependraChaddha** [comment]
Okay I guess I would look for some other issue
