### ISSUE TITLE
edit_where widget for backup path is not editable

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#349]
In settingsdialog.glade, the edit_where widget's "editable" property is False.

Three possible solutions:
- make it editable
- replace it by a label
- replace the two "edit_where" and "btn_where" widgets by a single GtkFileChooserButton (which solves everything in an elegant way). If you want this, I could maybe provide a patch/branch for it. See the attached screenshot to know how it looks like.

---

Imported from Launchpad using lp2gh.
- date created: 2011-01-31T01:21:21Z
- owner: kiddo
- the launchpad url was https://bugs.launchpad.net/bugs/710414

**Comment by Germar** [comment]
(by kiddo)

**Comment by Germar** [comment]
(by danleweb)
I'm not sure I get the problem:

1. In the beginning I used "GtkFileChooserButton" but I had some problems:
 - There is not way to set an empty value (like never set). This pose problems if you open the dialog and just save it. You may end up with a snapshots folder by default.
 - A simple mouse scroll by error can change it and I think this is dangerous

2. I don't want it editable (at least for now) so can select only valid folders (the dialog allow you to create new folders.

3. I'm not sure about a label but using a read-only editbox allow you to select the text, scroll if it does not feet.

**Comment by buhtz** [comment]
The report is old, related to Gtk but the situation described also exist in current BIT running with Qt.

But I don't see a problem. It is a none editable textfield. OK, this isn't maybe what all users expect and there is room for improvement.

But because the whole GUI need a complete rework and restructuring I wouldn't invest resources in such a tiny Issue. The issue will get fixed by the way while the complete redesign/restructuring of the GUI.

Keeping the issue open won't add value to BIT. Closing this because of it.
