### ISSUE TITLE
There is no way to recover hidden files or directories other than recovering its parent

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#378]
Backup hidden files either by .hidden or by .<name>
Those directories are backed up correctly but they do not show up on the snapshot file listing.
They can only be recovered by recovering their parent directory.

---

Imported from Launchpad using lp2gh.
- date created: 2011-08-15T22:18:42Z
- owner: mashimom
- the launchpad url was https://bugs.launchpad.net/bugs/826998

**Comment by Germar** [comment]
(by mashimom)
Also I am using the version on stable ppa.

**Comment by Germar** [comment]
(by danleweb)
The GUI has a button in the second toolbar (next to current path) to show / hide hidden files. 
By default hidden files are not showed. 
If you select to show hidden files you can restore them like normal files / folders.

Regards,
Dan

**Comment by Germar** [comment]
(by mashimom)
Thanks, I am aware of the GUI button and it was active.
I found more about it; it randomly hides some directories and files, to some extent it seemed to be jumping exactly one hidden file, but then I found a bunch of them were not shown.

Regards,
Marco

**Comment by Germar** [comment]
(by danleweb)
Can you check the user/group on this files ?
If they have the same user/group/rights as the files in the list that this is serious bug.

Regards,
Dan

**Comment by aritorhamo** [comment]
I think it's important to tell in the documentation how Back in Time works (and doesn't work) with hidden files. I just spent an hour trying to find how to get hidden files to show in the initial (settings) window that appears after installation (I googled the subject, and got an impression that it can be done). I can't be the first person stumbling there. Because "Show hidden files" is available in the main window, it makes sense to have it available in the file selector too. If it were, one would of course expect to be able to use it to select individual files. Is that somehow difficult to achieve?

Thanks,
Ari

**Comment by Germar** [comment]
The file-selector dialogs are default dialogs. There is no way to add a new button to show/hide dot-files. I just tweaked them to automatically show/hide dot-files depending on whether they are shown in main window.

I'm currently rewriting the documentation. And I'll include how to show dot-files there

**Comment by aritorhamo** [comment]
At least in my system (Ubuntu Gnome) Ctrl + H given in the file selector of Back in Time doesn't show  hidden files, although it works in the system dialog. Having the main windows behaviour transferred to the file selector is very helpful, thanks. 

One thing that caused me to stumble on this was the fact that when Back in Time opens, only the settings window is visible. I thought that it's the main window (silly of me, but I was tired). That's why I was looking for the "Show hidden files" button there (I read on a few other web pages that it is there (on the main window, in reality)). The instructions on other web sites weren't quite fresh, so I thought that the interface has just changed. I quickly visited the Back in Time documentation page at some phase, but moved on soon, because currently it's basically just a menu listing with pictures, not a real user guide. 

It's great to hear that you are working with the documentation. I think the documentation and the user guide would be best seen as an important part of the user interface. Same high standards and new-user-friendliness would be best applied to both.

My first back up with Back in Time is now done, and it worked great. Thanks!
