### ISSUE TITLE
initial partial backup (or resume) greatly desired 

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#400]
As backups become large due to all the photos people take (mine takes many hours), failing the initial backup due to one or two small errors is very frustrating and almost made me give up on the program.  I guess my point is that the initial impression is very important & you really want it to work flawlessly then.

I'd suggest the easiest soln is to have the "continue on error" CHECKED by default and add a bright red "PARTIAL" warning on the backup snapshot list (left chooser) if the backup has an error or gets aborted by a system shutdown, manual abort, program crash, kill, or whatever.  That way, the program can still use the data in partial backups to complete a full backup next time.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2012-01-11T15:54:28Z
 * owner: g-andrew-stone
 * the launchpad url was https://bugs.launchpad.net/bugs/914816

**Comment by obilodeau** [comment]
Was this implemented? If so, how, because the bugs don't say so and there is no UI feedback.

Context: I did the first full backup of a new laptop yesterday (200Gb+) because my server is an old ARM machine, it's pretty slow and it didn't complete (~100Gb done). Without a mean to cancel, I simply left with the laptop, backup failed somehow later. Now I try to do a new snapshot and the UI has been showing "Working: ..." for the past 20 minutes.

From what I can see, it is doing a 'rm -rf ...' over an sshfs mount. I wouldn't consider this a resume operation.

Why not consider failed snapshots as partially successful ones? Because I see a `new_snapshot` folder created yesterday. Is the hard-linking mechanism only between `latest_snapshot` and `new_snapshot` to avoid partial snapshots from creating larger backups due to a lack of hard-linking potential? If so, then how about this: when there is no previous snapshot, then don't remove the partial `new_snapshot` and consider it as a base for the new snapshot otherwise insist on having the whole thing. What do you think? I would be willing to try to contribute it.

Another thing to consider, doing the `rm -rf ...` over ssh instead of through sshfs would be tremedously faster on CPU bound servers like mine. A lot of traffic getting encrypted back and forth by a slow CPU while a local `rm -rf ...` generates no output.

I'm using full rsync mode.

**Comment by Germar** [comment]
`Continue on Errors` default on is implemented. But this has nothing to do with your case. `Continue on Errors` will continue (renaming `new_snapshot` to `20151120-223911-123`, store permissions...) after rsync returned non zero and mark the snapshot `with errors`. If you deactivate it BIT will delete the `new_snapshot` folder after rsync returned non zero.

Problem you're facing is that there already is a `new_snapshot` folder (from last run) which will always be deleted before taking a new snapshot.

This is partly necessary because if the last run broke during creating hard-links (without `Full rsync mode`) we would end up in an unknown state where rsync would create lots of new files without hard-links.

So we need to define states during runtime where it is safe to continue and add a `safe_to_continue` flag to the `new_snapshot` folder (just an empty file). In my mind this can be set before rsync start syncing. If the process was killed after this the next run will read that flag, skip removing `new_snapshots`, skip `check for changes` and `create hard-links` (`cp -aRl ...`) and just start rsync on the existing `new_snapshot` folder. In this way this would also work for subsequent snapshots. Not only the first.

It's quite easy to implement. If you would like to contribute this I'm happy to help. Just drop me a line

--------

Removing the `new_snapshot` folder over ssh drove me crazy when I added SSH mode. BIT didn't recognize that the `new_snapshot` folder was gone even when there was nothing left. Back then I had no other choice than removing `new_snapshot` through sshfs. But last week I found the root of the problem and a solution while working on #493. sshfs caches the remote files and folders. If you delete a file remote (not through sshfs) it won't recognize. I added a method to update the local cache (just write an empty file through sshfs and delete it again). In this way local and remote are in sync again. I was about to add this for deleting `new_snapshot`, too :-)

**Comment by Germar** [comment]
Hmm. The mentioned 'update local cache' method doesn't work here. No idea why not. But I changed delete `new_snapshot` to delete `new_snapshot/backup` through ssh and in a second step `new_snapshot` through sshfs. This way BIT will recognize it is gone...

**Comment by obilodeau** [comment]
Thanks for the information. I'm not sure I'll have time to contribute it before a few weeks so if you want you can always do it. I'm glad to see that you have a specific idea on what should be done to fix this!
