### ISSUE TITLE
SSH backup mode needs to pass a ping test

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#428]
Ping is blocked on some remote hosts, but a ping test is required in order to add an SSH-mode profile to BiT. Please remove the ping test in favor of a test that tries to SSH to the remote host instead.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2013-09-17T17:13:25Z
 * owner: bob-igo
 * the launchpad url was https://bugs.launchpad.net/bugs/1226718

**Comment by Germar** [comment]
(by germar)
added a port-check instead of ping

**Comment by mmeidlinger** [comment]
Is there a possibility to disable the ping test?
I have the following use case:
I'm running a central remote host to which I wish to send my backups to via ssh. Because this is a home user setup, the remote host sits behind a router performing NAT. So wether I'm on my local network or not determines how I need to access it via ssh.
Usually, I work around this by configuring my .ssh/config like this
```
Host router
   HostName mydomain.com
   User root

Host backup-host
   HostName 10.10.0.1
   User myself
   ProxyCommand ssh -q -W %h:%p router
```

I can then `ssh backup-host` no matter if I'm on my local network or on the go, and ssh connects via my router to my backup-host. However, while this ssh setup works perfectly fine, backintime's ping test does not seem to be happy with it. I'm aware that I could (and in fact I can) connect to a vpn and simply connect back in time via my local address 10.10.0.1, but this seems like a rather poor solution, considering that the ssh connection is actually there and working and it is just the ping test that prevents this from working.

**Comment by Germar** [comment]
This is done in #647. Please install current development version from our PPA:

```
sudo add-apt-repository ppa:bit-team/testing
sudo apt-get update
sudo apt-get install backintime-qt
```

**Comment by mmeidlinger** [comment]
Oh, great, thank you very much! I'm on Arch and have installed the AUR version backintime-git, so I was assuming that I already had the newest version. Thanks again!

**Comment by Germar** [comment]
Oh, sure. With `backintime-git` from AUR you should use the current master
