### ISSUE TITLE
Umount stalls on suspend or shutdown after backup using back-in-time gui

### ISSUE THREAD

**Issue by tbys** [bit-team/backintime#479]
This issue started occurring after upgrading BIT to 1.1.8 using the ppa at 

   deb http://ppa.launchpad.net/bit-team/testing/ubuntu trusty main 

What happens? The system is unable to shutdown or suspend, and umount hangs with cpu on 100%

My system is Ubuntu 14.04.3 64 bit.

I haven't had time for thorough testing, but the following steps seems to reproduce the problem

1. Boot & login
2. Connect external luks-encrypted usb drive 
3. Ubuntu automatically mounts the encrypted partition
4. Launch the BIT gui
5. Run a backup 
6. (Optional) unmount the drive
6. Initiate a suspend

At this point the screen goes black for a few seconds and then turns back on and displays the login screen. Looking at ``top`` I can see that umount has stalled. I am unable to unmount the drive or kill the umount process. Looking at dmesg I see no errors pertaining to the suspend operation, so it seems like suspend is actually successful but that the pegged process wakes up the system immediately.

**Comment by Germar** [comment]
When you said 'Ubuntu automatically mounts the encrypted partition' do you have a script which will do that or did you add the password to keyring and let Nautilus mount the partition automatically.

How do you unmount the device? Again, script or by clicking the eject button in Nautilus? Please provide these scripts (if any) and I'll try to reconstruct this here.

**Comment by tbys** [comment]
I have added the decryption password to my keyring and Ubuntu mounts the partition when I plug the drive into a usb port. For un-mounting, I right-click the icon in the Ubuntu launcher and select "Safely remove".

**Comment by Suor** [comment]
I have the same issue, it could be easily reproduced without BackInTime though.

My setup:
- Ubuntu 15.04 64bit
- External luks+ext4 USB HDD

Here is my way to reproduce:
- connect drive
- enter password (or be it retrived from keyring)
- drive mounts and works flawlessly
- unplug drive USB from laptop (without unmounting it first)
- unkillable umount is stuck at 100% CPU, trying to connect and mount drive results in "Operation pending" message

The only workaround I found is reboot. It also happens if I suspend laptop (shut the lid) and then unplug, which is very easy to do accidentally. I beleive it's an issue with luks - everything worked fine before I encrypted the drive.

@tbys if this procedure also "works" for you then we should move this bug elsewhere.

**Comment by tbys** [comment]
Thanks for pitching in. It does seem like @suor is correct in the assumption that this can be reproduced without BIT.

I tried your first method (connect-mount-unplug) @suor (thanks for pitching in), but it doesn't reproduce the issue on my system. 

However, the suspend-then-immediately-unplug method that you also mention *does* cause the umount stall. 

I also managed to reproduce the stalled umount without BIT, with the following method:

* connect drive
* drive is automatically unlocked using password stored in keyring
* open a file somewhere on the mounted partition, e.g. ``vi /media/username/foo``
* kill the process with which the file was opened, e.g. ``killall -9 vi`` 
  * this leaves the file handle hanging around as far as I understand
* unplug the drive

However it also still reproduces with the method in my initial post, so perhaps BIT leaves file handles open under some circumstances? I should add to my method above, that the BIT GUI status indicator says "Done" before I initiate the suspend. 

@suor is it possible that in your case, something is opening a file on your drive when you mount it?
