### ISSUE TITLE
Target directory not being created via SSH

### ISSUE THREAD

**Issue by silvavlis** [bit-team/backintime#520]
I'm using BiT 1.1.12 (PPA for Ubuntu 15.10) over SSH and when trying to create a new profile it fails with the error:
> [E] Error: rsync: mkdir "/path/backintime/host/user/profile/new_snapshot/backup" failed: No such file or directory (2)
> [E] Save permission over ssh failed. Retry normal method

If I manually create the directory that rsync is trying to create, then it works properly. So apparently BiT isn't creating the top directory expected by rsync.

I've been using 1.1.8 in the past without problems, so possibly this is a new issue being introduced afterwards...

**Comment by Germar** [comment]
I can't reproduce this here and on a quick diff of all changes between `1.1.8` and `1.1.12` I didn't notice anything that could cause this.

But your error messages very much looks like you're using a Synology NAS which is (most probably caused by a recent firmware update) not prepared for BIT like [described in our FAQ](https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-synology-dsm-5-with-bit-over-ssh)

**Comment by silvavlis** [comment]
You are fully right with everything. Sorry for the unneeded issue... I just didn't have a script to automatically create the bind mount and after a reboot it didn't work any longer. It was just a coincidence, that I updated BiT almost simultaneously.

**Comment by Germar** [comment]
No worries mate
