### ISSUE TITLE
need to get "--restore" CLI feature, but running CentOS 6 with BIT v 1.0.8

### ISSUE THREAD

**Issue by tommybutler** [bit-team/backintime#531]
I need to be able to do "backintime --restore" from the CLI on all my Linux installations.

   * This works OK on my and CentOS 7 hosts

   * It isn't available on my CentOS 6 hosts which run BIT version 1.0.8.

The backintime RPM's for CentOS 6 don't offer any higher version than 1.08, and I'm not going to be able to upgrade the CentOS 6 Linux installations for several months.

How can I get `backintime --restore` on these CentOS 6 installations?  What options do I have?

**Comment by Germar** [comment]
You can manually install a more recent version. If CentOS6 support Python3 choose [latest version](https://github.com/bit-team/backintime/releases/latest) if not use [version 1.0.40 from old branch](https://launchpad.net/backintime/1.0/1.0.40).

Take a look into README for dependencies and install instructions.

**Comment by tommybutler** [comment]
@Germar CentOS6 does not come with python3, and the 1.0.40 branch of BIT doesn't have the "--restore" feature.  This means I need to do two things:

1. create a standalone python3 installation so that it doesn't interfere with the default system python installation
2. install the most recent BIT release in such a way that it uses the standalone python3 install

Is it possible to do this with http://www.pyinstaller.org ?

**Comment by Germar** [comment]
`--restore` was introduced in 1.0.26. So 1.0.40 has it, too ;-)

At least `python-dbus` and `python-keyring` are necessary dependencies beside `cron`, `rsync` and `openssh-client`.

**Comment by tommybutler** [comment]
@Germar thanks for the reply.  Let's assume I want to keep up with the latest release and _all_ its features as well...

What would you recommend so that I could achieve this on a Linux system that only has official rpm/deb packages for python2?  A lot of companies are still running RHEL 5.9 and 6.x and I want to create a solution that will enable me to run the latest BIT on these platforms.

**Comment by tommybutler** [comment]
Thank you @Germar

**Comment by dinoboy197** [comment]
@tommybutler - in my experience, your situation is both a blessing and a curse - some distributions remain "supported" (and go used in production) for many years because they can remain "feature stable", but that stability is very often at the cost of not backporting new packages, features, etc that might cause regressions. Stability is a double-edged sword, in that case :(

Certainly, installing python 3 and all of the dependencies on an older system could be possible - manually - but I have to imagine that it might invalidate any RHEL support contracts (which say that you can't muck around in the system on your own) or possibly even destabilize a production system if you start hand compiling binaries and stuffing them into `/usr/local` or `/opt/local`. At least, that has been my experience in larger corporate entities which run RHEL.
