### ISSUE TITLE
Will data recover if source drive crashes ?

### ISSUE THREAD

**Issue by saxenaakash** [bit-team/backintime#548]
Hi
i am trying to create a backup as following :
source : Hard diskA - NTFS
backup location : Hard diskB - Ext3/4
since only hard links are being created,
1) will i be able to recover data to the NTFS drive someday ? (i dont know if NTFS supports hard links)
2) will i be able to recover data from diskB (to a new disk) if diskA crashes completely ?
thanks for your work !
akash

**Comment by Germar** [comment]
Hi akash,

1. sure, that will work. NTFS supports hard links but recover would work without hard link support, too.
2. of course. Just add a new drive, format it and you can restore your files.

Regards,
Germar

**Comment by colinl** [comment]
> since only hard links are being created
I wonder whether you are confused about the way BIT works.  Hard links are used (as I understand it) when successive snapshots contain files that are not changed, then a link is saved in the snapshot instead of another copy of the file.  However when a file is first added (or is modified) then the file is saved in the backups, the links in subsequent snapshots are to the previous file in the backup, not to the original file on the source disc.

**Comment by saxenaakash** [comment]
Germar and colinl,
  thanks for prompt and clear answer !

@colinl,
  yes, that exactly was my concern ! i was concerned that the first backup itself would have hard links. looks like i missed reading this point in the description on homepage. apologies.

  i had already downloaded and ran the BIT before creating this issue. it worked so fast for the first backup that i was convinced that even the first backup is hard links !! i am used to Deja Dup's slow, slow performance. thanks for amazing work !

akash
