### ISSUE TITLE
Feature Request: Check Integrity Of Snapshots

### ISSUE THREAD

**Issue by rain0r** [bit-team/backintime#571]
Since I had some turbulences on my backup disk I would like to know if my saved snapshots are still intact. 
It would be nice to have a feature which checks the integrity of saved snapshots and alerts the user if they are modified.

**Comment by Germar** [comment]
There is no way this could be done for old snapshots because BIT does not have checksums or anything else to compare the old files with.

But to eliminate corrupt files in future snapshots you can take a new snapshot with the `--checksum` option (`backintime backup --checksum`). This will make `rsync` to compare local and destination checksum to decide if the file had changed. Take a look at the [FAQ article](https://github.com/bit-team/backintime/wiki/FAQ#how-to-use-checksum-to-find-corrupt-files-periodically) about that.

**Comment by buhtzz** [comment]
@emtiu Close.
