### ISSUE TITLE
Transfering backup from Backintime to new machine

### ISSUE THREAD

**Issue by afettouhi** [bit-team/backintime#573]
I've been doing regular backups from my Arch Linux 64 bit workstation with backintime onto my fileserver. I plan to this month to build a new workstation and do a fresh install of Arch Linux on that. So my question is, how do I restore a backup from my old workstation to my new workstation with backintime. Is it even possible?

**Comment by Germar** [comment]
Sure it is possible! (Would be a lousy backup system otherwise :wink:)
Just copy your `~/.config/backintime/config` and your private key (if you use SSH mode) `~/.ssh/id_rsa` from your old machine over to the new machine. You might have to provide the password for the private key at the first start of BackInTime on the new machine but everything else should run without problems.

**Comment by afettouhi** [comment]
Thanks the quick answer. Justr what I wanted to hear. :+1:
