### ISSUE TITLE
BIT, Snapshots, Hard Links, & NFS

### ISSUE THREAD

**Issue by JoTraGo** [bit-team/backintime#574]
I have been using BIT for a while now getting it set up to backup my Laptop to my Synology DSM NAS box. BIT backups are running as per schedule.
My NAS box runs out of space very quickly, and it appears that it sees all BIT snapshots as full.
Investigating Hard Links, here and elsewhere it appears that Hard Links to files on a local file system cannot be made to a remote file system, NFS mounted on the local file system.
Which probably explains my issue.
I saw the issue https://github.com/bit-team/backintime/issues/526 which recommends using SSH rather than NFS, and I also see there is a How To for SSH with Synology DSM in the FAQ, so I will look into this.

However I am looking for clarification as to IF and HOW, BIT snapshots can work with a NAS system (even via SSH).

My (limited) understanding of Hard Links is that they are extra pointers, in addition to the original file name, to the INode of the file. It would seem therefore that any query of the size of the Hard Link would return the full size of the original file. So how can a BIT Snapshot appear smaller then the full size?

Thanks

**Comment by Germar** [comment]
That's right. A hard-link is just a new path to the inode and it will increase the link-counter of that inode. Take a look at [this FAQ article](https://github.com/bit-team/backintime/wiki/FAQ#how-does-snapshots-with-hard-links-work).

If you check the size of one or an other snapshot it will always appear as they took the whole size on disk. But if you run `du` on snapshots parent folder you'll see they don't take the full size. But even that is irritating because `du` doesn't scan the folders chronologic. And so will it look like a random snapshot took the whole space instead of the very first one.

**Comment by JoTraGo** [comment]
So that would suggest that the only circumstance under which one would realise the space savings of Hard Link Based snapshots is if the Backup Target is on the same filesystem as the source data, an unlikely scenario.
In the more likely scenario of backing up to a different filesystem either HardLinks will not work at all, or the target filesystem will perceive all snapshots as full?

**Comment by Germar** [comment]
No, not at all. Source files and snapshots are never hard-linked. Even if they are on the same filesystem.

As long as the target filesystem support hard-links, snapshots will be incremental.
