### ISSUE TITLE
Restore the correct file owner and group fail if they are not present in system

### ISSUE THREAD

**Issue by Germar** [bit-team/backintime#58]
If the user/group is not set up in the system which is running a restore BIT will fail to restore the owner/group of a file. It will fail with 'Failed to get UID for FOO: getpwnam(): name not found: FOO'

At least without 'Full rsync mode'. Could be different if 'Full rsync mode' is activated (not tested yet).

WORKAROUND:
This will happen if you restore your system from a LiveCD. Booting the restored system into recovery mode and running 'backintime --restore' again on root terminal will help for now.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-09-13T20:38:55Z
 * owner: germar
 * the launchpad url was https://bugs.launchpad.net/bugs/1495295

**Comment by s4448** [comment]
I'm the guy who had problems with this and who you, @Germar, helped on AskUbuntu. And while I'm grateful for the help, and very positively impressed with the fact that a developer browses the tag associated with his software to answer questions, I also want to give you my opinion on the issue from a user's perspective.

To me this seems more like a fundamental design error than a bug. 

One of the main appeals of BackInTime is the fact that it copies the files as they are, instead of sticking them into some weird, own format like a lot of backup tools do. But if file permissions can only be restored from the same system that they were taken from, and if they are not restored, system breaks - ergo, system backups can only be restored from the same system that they were taken from - then that means BIT is actually significantly worse than the above-mentioned backup tools. With those, you maybe needed the tool for every restore, but at least it works across systems. 

More even - not only is it worse, but it *appears* to be better. It appears to be just a GUI for automated, smart copying of files without messing with them. And because it appears to be like that, and it's very much not like that, it deceives the user in a way. A user will install it, configure it, then test it thoroughly, and he probably will do the tests from the system he uses it on, so everything will work. And then when the system breaks and the user tries to restore it, it doesn't work. And there were no warnings about this, no errors pop up when the restore fails with permissions, nothing to indicate that this is a BIT thing and not the user himself messing something up. As you can imagine, that can lead to a lot of wasted time and a lot of frustration, as it did with me.

Now, I'm not trying to blame anyone here for that, BIT is open-source and comes with no warranty, and so if something doesn't work, the fault is mine alone for relying on it with important stuff, and I should be grateful that the software is there in the first place. I understand that.

But at the same time, I wonder how many people will end up really frustrated just like me, because a tested system that is based on simple, long established tools, is not working and they have no idea why.

For any decent piece of software, it is vital for it to communicate to the user what it does without creating huge misunderstandings.

You said something about loading a different /etc/passwd, but there will be a lot of use cases where this doesn't work. What if I'm booted from a LiveCD, restoring files on a disk that is from another system, but does not contain the system itself, and I want my permissions back? There is no right /etc/passwd to load, neither on the system that runs BIT nor in the backup itself.

This is just my opinion, but I think BIT should not touch the permissions in the first place, but rather copy them as they are, as it is supposed to do. As far as I understand, BIT makes all files in the backups owned by root to protect them from accidental deletion. This is a cool little feature, but is nowhere near important enough to justify making BIT utterly useless for system backups. If anything, this should be an option buried deep in the settings menu and with a warning saying exactly what consequences it will have if enabled.

Now, if you disagree with me and want to keep the changing of the permissions, that is perfectly fine. But please, put a big, red, all-caps warning that pops out during installation, saying that this software should never be used for system backups, and when doing file backups you should say bye-bye to the permissions. And put a similar warning on the website.

That said, thank you again for the help, and for developing a cool piece of software.

**Comment by Germar** [comment]
Thanks @s4448 for your opinion. I know this is a serious bug. But the bugreport is only three month old. There can't be any warnings about this in older versions because I didn't know about this before.

I also wouldn't call this a design error. Back in the days when Dan wrote BackInTime and decided to put permissions into an extra file this was done because many people using NTFS (or even worse FAT) formatted drives for backup. So there was a need to separate permissions from FS. Since ~two years there is a new option `Full rsync mode` which will store permissions with the FS but even this will have troubles with permissions if you restore on a system with different `/etc/passwd`.

-----

So, to fix this I will add a function to always backup users/groups settings which will be used in first place when restoring. But there also need to be a function to read in a different `/etc/passwd`/`/etc/group` because the snapshot was done with an older version and miss that additional infos.

**Comment by s4448** [comment]
If you can do that, then yes, that solution seems to be the very best one, getting the best of both worlds. And I see your point with the NTFS drives.

So thank you for the good response and for fixing this.

**Comment by Noctiflore** [comment]
In my opinion, adding functionalities to handle conversion between passwd files is not necessary, nor a good idea as it is not generic and outside the scope of a backup tool.

IMHO, the real design mistake here is to use usernames, and usernames only (or even just "-" if there is no match at backup time) in fileinfo : it should store users IDs, as filesystems do.
Also note that rsync itself provides good solutions to cope with this problem in most situations (when transferring from a system to another), described in its manpage under the --numeric-ids option description.
Other archiving tools like tar/cpio/pax allow to store and use both users names and numerical IDs.

**Comment by Germar** [comment]
@Noctiflore I started working on BIT long time after the decision on using usernames was made. But I think this was for a good reason because when you restore your files on a new machine the uid/gid might be different. For example if you created new users in a different order than you did on your old machine.

The fix in commit [1734ae3](https://github.com/bit-team/backintime/commit/1734ae36a018db1a83960044d67d721e2952ad1e) will backup uid/gids as well and on restore try to get the current uid/gid from system and if that is not present it will use the backup.

**Comment by Noctiflore** [comment]
What you implemented is very similar to the default behaviour of Rsync (without --numeric-ids) ; that's OK for me.

Thanks for the fix !

**Comment by efficiosoft** [comment]
I want to pick up this issue again.

I'm using BIT to backup a hand full of machines regularly. I'm backing up via ssh to a btrfs file system, hence I use ``full_rsync = true``.

Today I needed to restore a whole OS via GRML live system and noticed that owners/groups where mixed up - what is the behaviour you described in your last comment, @Germar.

That concept has some awful consequences when used to restore via live systems. For instance, the user ``vnstat`` was present on the live system as well as on the system I was going to restore. BIT now chowned ``/etc/vnstat.conf`` to the ``vnstat`` user of the live system, which had the same UID as ``postfix`` on my regular system. After rebooting, ``/etc/vnstat.conf`` was owned by ``postfix`` - which is crucial.

Fortunatelly I used ``rsync --fake-super --numeric-ids`` at the time of backup, thus I could easily remove the ``fileinfo.bz2`` and ``info`` files and run BIT again, what caused it to abort after rsync had fixed the problem on its run.

My suggestion is to add a config switch called ``numeric_ids`` that
* adds ``--numeric-ids`` as parameter to rsync when run in ``full_rsync`` mode
* always uses UID/GID stored in ``fileinfo.bz2`` when restoring, no matter if a user/group with the same name exists in currently active passwd/group file.

What do you think about it?

Best regards
Robert
