### ISSUE TITLE
How long should BIT take to complete "smart remove"?

### ISSUE THREAD

**Issue by jeffsilverm** [bit-team/backintime#611]
I have set backintime to do "smart remove".  The job has been running for two days and if my calculations are correct, it should finish around 39 hours from now.  I have been running
 ```tail -f ~/.local/share/backintime/takesnapshot_2.log```
and noting the progress - it is currently at 283/637.  Is this unreasonable?  Should I have done more housekeeping before I started backintime?  Because the lock file ```~/.local/share/backintime/worker2.lock``` is still present, no other snapshot can run.  I would like to run a snapshot every 30 minutes.  Is my expectation unreasonable?  Is the smart remove problem going to sort itself out, eventually?  My intuition tells me it will, because as it decides to stop saving old files, the backups will run faster.

I also have a question about looking at the log files.  First of all, is there someplace I ought to look that says how to read a log file?  I am looking at ```~/.local/share/backintime/takesnapshot_2.log``` .  This is what is going to be the log file for the snapshot, but by tailing it, I can watch the process in real time.  It says that the snapshot started at Tue Aug  2 10:30:02 2016.  In this log file, there are 291275 lines with "[C]".  There are 17695 lines that begin with "[C] cd",  226372 lines that begin with "[C] >f", 34320 lines that begin with "[C] hf", 5 lines that begin with "[C] cS" (those are all named pipes), 12286 lines that begin with "[C] *deleting" and 597 lines that begin with "[C] cL".  There are 278688 lines that contain the string "++++++".  So either hf or >f are files.  

If I use the ls -l -u command on the file system I am backing up, I can see that these directories have been "used", and the time stamps are consistent with something going through the file system around 10:30 AM Tuesday.  However,  a lot of the files have not been used since July 28th, July 21st, or July16th.  So that's consistent with my experimenting to see what works.  So clearly, backintime is working as it is supposed to, I just don't understand it well enough yet to "tune" it to do what I want.

**Comment by Germar** [comment]
Hi Jeff,
yeah, you should have switched on `Smart Remove` earlier. Also IMHO a new snapshot every 30min is a bit overkill. I used to run a new snapshot every 4 hours with the `Repeatedly (anacron)` schedule.

Deleting old snapshots will NOT speed up future backups. A new snapshot will always compare only with the very last snapshot. So it doesn't matter how many other snapshots you have.

I improved the remove process in the current dev version. It now uses one single rsync command to remove the whole snapshot instead of running `find -type d -exec chmod u+wx {}+` and `rm -rf` for each and every snapshot. So if you don't mind running an alpha version you could kill the current progress and upgrade (`ppa:bit-team/testing` if you're on Ubuntu)

There is no doc yet for the log file. The part after `[C]` comes from rsync. Take a look at `man rsync` section `--itemize-changes`.

Regards,
Germar
