### ISSUE TITLE
Can BackInTime archives be manipulated by rsync?

### ISSUE THREAD

**Issue by sudhirkhanger** [bit-team/backintime#627]
Hello,

If I have back up made by BackInTime can they be manipulated (extracted and added to) by rsync? How compatible is BackInTIme with Rsync?

Sudhir.

**Comment by Germar** [comment]
BiT it self is just a fancy front-end for `rsync`. It uses `rsync` itself to sync the files. So it is 100% percent compatible. But BiT also do some more things, too. Most important regarding your question it creates a file with permissions (owner/group and read-/write-/executepermission) for all files because not all destination drives are capable to store them by their own and even if they do, the user might not have permission to change all those permissions. So if you manipulate your snapshots and restore it later you might find the permissions lost for the files you added manually.
