### ISSUE TITLE
Is this tool meant for taking entire system snapshots?

### ISSUE THREAD

**Issue by smurfendrek123** [bit-team/backintime#688]
I'd like to take 2 snapshots of the entire system, seperated by installing some software, is this tool good for that? So when i'm not happy with something i've done, i can just go back to one of my snapshots.

I've looked into using lvm snapshots, but if you take multiple ones, changes get written to each snapshot instead of just one.

**Comment by Germar** [comment]
You can take full system snapshots. But I wouldn't recommend it for your use case. Because if you want to go back to an earlier version you'd also need to delete newer files. BiT can do this, but it would also delete all files which where excluded while taking the snapshot. And because couple system files are excluded by default this would break the system.

**Comment by smurfendrek123** [comment]
Thanks for the answer, i moved onto using btrfs for this.
