### ISSUE TITLE
Restoring a test directory in root mode made system almost un-bootable.

### ISSUE THREAD

**Issue by W0nderer** [bit-team/backintime#708]
I have been learning how to use Back in Time using a test directory (Test-BIT) in my home directory.   I put ~/Test-BIT in the Include list of BIT's main profile and took several snapshots while creating and deleting a few text files and a directory within Test-BIT.  I was using BIT in root mode as I had hoped to eventually be able to use it to back up /root as well as /home and data directories.

I did a restore by: selecting a backup date in the Timeline; selecting Test-BIT in the Snapshots list; clicking Restore; confirming that it should be restored.  The restore completed within a few seconds and seems to have restored the directory Test-BIT to it's previous state perfectly.  Unfortunately it damaged other parts of the system so badly that it became un-bootable, except in single user mode.

Immediately after the restore completed there were symptoms that something had gone seriously wrong, including:
-  The colour of text and icons in BIT's title bar changed from white (on blue) to black.
-  In Dolphin files had text but no icons.
-  Sub-menu items in KDE's Application Menu had icons but no text. 
-  Attempting to run commands from it gave Plasma errors "Unable to run the command specified. The file or directory ... does not exist.", even though they still did. 
-  Firefox pages no longer loaded.

Fortunately I had a root shell open in Konsole, but found that even as root:
-  Doing an ls -l of my home directory gave my user id instead of name.
-  Running the man command gave the error "man: Failed su to user man".
-  Opening a new tab for root or myself gave an error message: "Warning: Could not find an interactive shell to start".

Even doing Ctrl+Alt+F1 and trying to login at the console as root or myself gave "Login incorrect".  After shutting down the system was still bootable, but only in single user mode.  After init'ing to run level 2 any attempts to login always gave "Login incorrect".

I realise that running in root mode is always potentially dangerous but what is really worrying is that Back in Time must have somehow damaged something outside the small directory in my home directory that was being restored.  Even if it had completely corrupted that directory the rest of the system should have been unaffected.  Being logged in as a normal user would have prevented it from damaging system files, but could it have still corrupted other files in my home directory?  Can you explain what is going on please, why is it changing other parts of the system?

The problem occurred using version 1.1.12 in openSUSE Leap 42.1 with a KDE Plasma desktop.  I originally installed version 1.0.6 from openSUSE's main repository but after finding several problems with that version I upgraded to 1.1.12 from their backup software repository.  The backup I restored might have been taken with version 1.1.6, could that have caused problems?

Fortunately I had drive images of the entire system and have been able to get it working again by restoring from those those.

**Comment by Germar** [comment]
I'm sorry for your problems. I tried to reproduce it on openSUSE Leap 42.1 exactly like you did but this didn't happen. I must say, I'm a bit stumped on this. The restore function will use rsync to sync the files from snapshot into the original folder. This doesn't touch any files outside the original folder respectively outside the chosen destination folder (when using `Restore to...`). In the last step BiT will restore permissions of files and folders for all restored files and the whole folder structure up to the restored folder. This would change things outside the original folder. But in your case, if it messed up, it would only mess up permissions of `/home` which wouldn't be so dramatic to render a system unbootable. At least `root` should be able to login if `/home` is messed up. Did you use the plain `Restore` feature or `Restore and delete new files`?

By any chance, did you keep the broken system (image)? Or do you still have the logs?
Which filesystem do you use? Did you check for harddrive problems (SMART warnings)?

Please don't get me wrong. I believe you about the facts and I definitely want to chase the problem down as this is really serious. But at the moment I'm baffled.

**Comment by W0nderer** [comment]
Thanks for investigating this and explaining how BiT does the restore.  After the problem I booted into a fairly new install of openSUSE 42.2 in another partition to see if I could spot any obvious problems in the oS 42.1 partition.  I wondered if the no multi-user problem was because /etc/passwd had been modified, but it had an old modification date and still seemed OK.  I also used Kfind to look for any system files that had been modified around the time of the restore, but couldn't see any.  Would changes to permissions or ACLs change the modification dates?  Although I couldn't see any suspicious changes to the system files something must have changed for the no multi-user problem to have persisted across a re-boot, mustn't it?  I too am baffled by the somewhat conflicting evidence at the moment.  It's possible that my system already had a hidden problem that I wasn't aware of and the restore revealed it, but I don't see how.

To answer your questions:
- I don't remember being given a choice when I pressed the restore button, just asked to confirm, so assume it was whatever the default restore is.
- Unfortunately I didn't keep an image of the broken system.
- The snapshot and restore logs should be attached.
- /home is in the root file system, both it and the the backup directory are ext4 with extended attributes and ACL enabled.
- I didn't look for any hard drive (SSD) problems, but haven't had any before or since

I will do some more tests over the next few days to see if I can come up with a repeatable experiment that you can reproduce, based on a new install of oS if possible.

[takesnapshot_.log.txt](https://github.com/bit-team/backintime/files/792008/takesnapshot_.log.txt)
[restore_.log.txt](https://github.com/bit-team/backintime/files/792009/restore_.log.txt)

**Comment by Germar** [comment]
<strike>Just an update on what I currently observed on your logs:

- You restored `/` so rsync did run on the full file-system. This was most probably caused by #687 but in my tests this never killed the system
- rsync did something with `/home` and `/home/me` as it is listed under `building file list ... done`
- BiT changed permissions of files it didn't touch during restore which is strange by it self...
- BiT also changed permissions of `/home` and `/home/me`. Normally BiT only change permissions if they do not match with those in the backup. `/home` should have `755` by default, so I'm not sure what was going on here</strike>

----

Huuuuuuh!!! :flushed:
I just reproduced it :flushed:
Looks like it is this is related to ACL or xargs. I didn't activate them before and tried again now. And immediately after restoring my VM died...
It behave exactly like you said. Even the restore log was the same.
Okay, so now I have something to test. But that has to wait for next week. Need to go sleep now and won't have time this weekend...

**Comment by W0nderer** [comment]
Great news, well done, have got further than me. 
I shall be interested to know exactly what it did to the system and if there's a way to repair the damage in such cases.
Have a good weekend.

**Comment by Germar** [comment]
Here is what I found out so far:
- it's definitely caused by #687. It won't happen if you only restore one file/folder. Only if BiT (accidentally) restores `/`. 
- it doesn't matter if you choose `Preserve ACLs` or `Preserve xattr` or both of them. It will always kill the system.
- on file to file basis there are no changes. I made two snapshots before and after restore, mounted them and compared them with `diff` without any differences. But for sure the binaries differ.

**Comment by Germar** [comment]
"Good News" is, this only happen on OpenSuse. It's not reproduce-able on neither Ubuntu nor Arch. That's also the reason why I didn't stumble over it before as I only test on Arch and Ubuntu.

**Comment by W0nderer** [comment]
I'm even more interested now to know what the problem is.  
openSUSE's stable releases (as opposed to rolling Tumbleweed) are usually fairly leading edge but reliable, especially around core functionality that you might be relying on.

**Comment by Germar** [comment]
No doubt, me too!

**Comment by Germar** [comment]
:flushed: This **does** happen on Ubuntu (and probably Arch), too. I just had the wrong assumption, this was related to ACL and/or xattr. As there was no changes on both for 1.2.0 I used that version for testing...

Here is what happend:
- in `1.1.12` and before by default BiT didn't use the `Full rsync mode` (in `1.2.0` this is the only available mode)
- without `Full rsync mode` BiT stores permissions inside a separate file and uses `--no-p --no-g --no-o` with rsync to skip syncing permissions to destination. After syncing BiT used `chmod -R a-w` on the new snapshot to make it read-only
- not yet sure why, but the file with permissions doesn't have an entry for `/`
- in combination with ACL and/or xattr BiT used `-pEgo` instead of `--no-p --no-g --no-o` to sync the permissions (necessary for both)
- when you pressed restore first thing which went wrong was #687. You didn't select a file in right hand pane and so BiT accidentally restored `/`
- because of `-pEgo` it synced the read-only permissions from snapshot onto destination
- after syncing BiT restored permissions for all files except `/` as there was no entry for it in permissions file
- so you ended up with a filesystem not read-able for everyone but root which made the whole system crash immediately

Sorry again for the troubles you had
Kind regards,
Germar

**Comment by Germar** [comment]
If this will ever happen again for someone using an old version, first thing: don't panic!
All you need to do is to boot a Live System, mount your old system and fix the permissions:

```
sudo mount /dev/sdaX /mnt
# where /dev/sdaX is your root partition
# use 'sudo fdisk -l' if you're not sure
sudo chmod 755 /mnt
```
Let me know if you need help and sorry for your troubles...

**Comment by W0nderer** [comment]
Thanks for explaining how to recover from the problem.  
Were all the other permissions below "/" on the path down to the folder being restored set to their correct original values?

**Comment by Germar** [comment]
Yes. All other permissions are restored correctly. Only `/` was missing in the permissions file and so it kept the wrong permissions.

**Comment by TheNomad11** [comment]
Thanks one million times. It seems you saved my day. Don't understand why this bug still exists or why there is no big warning about this program. This happened to be on the newest Linux Mint just after backing up a test folder. Laptop unresponsive and then not bootable. Dangerous program that should not be used by anyone!

> If this will ever happen again for someone using an old version, first thing: don't panic!
> All you need to do is to boot a Live System, mount your old system and fix the permissions:
> 
> ```
> sudo mount /dev/sdaX /mnt
> # where /dev/sdaX is your root partition
> # use 'sudo fdisk -l' if you're not sure
> sudo chmod 755 /mnt
> ```
> 
> Let me know if you need help and sorry for your troubles...
