### ISSUE TITLE
Backing up to nfs share: Unbelievably slow

### ISSUE THREAD

**Issue by heis2201** [bit-team/backintime#757]
Hi,

I am using backintime over NFS to backup my workstation. Both workstation (nfs client) and backup server (nfs server) run Fedora 24.

The network (1000M) seems fine. I can transfer large files with high speeds (>120 MB/sec). A manual copy of my files over NFS is not as fast (because of many small files) but still acceptable.

This is not the first snapshot, and Backintime gives stats like Speed: 15-30 kb/sec, ETA: >3000hrs.

How can I understand and debug this problem and what tweaks would be possible here?

Thanks

**Comment by Germar** [comment]
The speed value is a bit misleading here. Rsync does calculate the size of all transfered data by the whole time. But because on NFS shares it will take a while to check if files have changed the overall transfer speed looks quite low. It is actually faster but like I said, most of the time rsync is seeking for changed files.

I'd recommend using BiT with SSH mode. This is a lot faster (six times faster in my case) because rsync will run on the remote host and only sync missing parts of changed files over the network.

**Comment by heis2201** [comment]
Thanks for your reply to my concern. I will give SSH a try - what you explain makes sense to me.
