### ISSUE TITLE
Support for Microsoft Windows

### ISSUE THREAD

**Issue by ispmarin** [bit-team/backintime#774]
Hi all,

I´m currently moving from a Debian system to a Windows 10 installation and have been a BackInTime user for a long time. I was wondering if there are any ports to Windows and if that option was ever considered, in case these ports don´t exist. 

Please, this is not a flamebait. I like BackInTime very much and would love to have it wherever I have to work, if possible. Huge kudos to the entire team!

**Comment by Germar** [comment]
Theoretical this should be possible. But it would be quite some work and I only have very limited spare time. I accept PRs :wink:

**Comment by MathiasRenner** [comment]
@ispmarin Which software are you using now on Win10 as a viable alternative for BackInTime?

**Comment by ispmarin** [comment]
@MathiasRenner I switched back to Debian. After some time researching I was not capable of finding a similar software for Windows. 

I'm using a combination of BackInTime to back up in an external drive with ext4 and SpiderOak One Backup for encrypted backup in the cloud. So far when I need to share some files between my linux boxes and a Windows machine I use Google Drive with https://github.com/odeke-em/drive for sync. Suggestions to improve this workflow are welcome!

**Comment by buhtz** [comment]
I am using [Unison](https://www.cis.upenn.edu/~bcpierce/unison/download.html) for syncing machines in local network. But this only makes sense when you don't use them paralel!

For other data I use ownCloud because my company offers a server instance. But you could install your own server instance if you have server available.

**Comment by blakemcbride** [comment]
It may not be that hard to port if cygwin were used.

**Comment by buhtz** [comment]
Using cygwin would be hard. ;)

BIT is written in Python - this is plattform-independed by design. It would be easier to check the code on plattform-dependend things - e. g. a lot of file handling. Maybe this issue would be a nice place to collect detailed informations about it and create a ToDo-List which parts of the code are related here.

I would support testing a Windows version of BIT because I have to use Windows on my company. But I also have no ressources to analyse and port the code.

**Comment by andife** [comment]
The thread sounds very interesting, but unfortunately not so active? Are there still considerations / actions in the direction of a port to Windows?

**Comment by buhtz** [comment]
I'm involved in that Issue for the last 5 years. 👴 😆 
Now I know the code basis and can say this is only theoretical possible.

One point is to make the existing code basis real platform independent. That is not a problem but just a lot of work.

The more important point is the missing `rsync` for Windows. There are some clones arround but they only use a subset of features of the real rsync. Windows do support hardlinks (aka junctions) but I don't know if the Windows-rsync-clones do use that. There are a lot of features that should be tested first. And there are some other external tools BIT is using. I see now way and no real value.

The platform independence of BIT code will come because we refactor and evolve that code. But the problems with external tools (most of them `rsync`) seems to be a damn hard problem. IF someone is out there and will take that challenge, we will support with our BIT knowledge.
