### ISSUE TITLE
How to back up hidden files only in /home?

### ISSUE THREAD

**Issue by susedroid** [bit-team/backintime#784]
I would like to back up only the hidden files in my home directory but cannot seem to get it to work using the GUI.

When in the Include tab I try using the wildcard .* to choose all hidden files but the open button is greyed out. Any clues as to how I can backup the hidden files only?

**Comment by DecoDogs** [comment]
From the GUI, select 'settings' and select the backup job of interest.  Go to the 'include' tab (the following also applies to 'exclude') and select 'add file' (this also applies to 'add folder').  

Right-click in the file (or folder) window and select 'show hidden files'.  By using either ctrl or shift, you can select multiple files (or folders).

I'm sure there's probably a magic better way :)


BiT 1.0.34; Linux Mint 17.3

**Comment by Germar** [comment]
Due to the way BiT handles includes it is not possible to include with wildcard. You need to include a whole file/folder.
But you can exclude with wildcards. So you can include your `/home/user/` and add an exclude rule which excludes everything that doesn't start with a dot `/home/user/[a-zA-Z0-9_]*`
