### ISSUE TITLE
Forced to perform Hard Restart after full system restore

### ISSUE THREAD

**Issue by Auronius** [bit-team/backintime#799]
Good day!
I have created full system backup, using the **Modify For Full System Backup** option in Settings dialog. The snapshot was created successfully, and was saved on the same hard disk. After some time, I have performed system restore, which has performed successfully, except one thing. After restore I had to do the Hard PC Restart using **Reset** button on my PC case, because when I tried to restart normally, using START menu, the system hanged. Then I have performed full system restore again, and after success, I tried to restart using terminal (sudo reboot). Again system hanged. 
So, the only way to reboot system after restore is to press Reset button on PC case.
Is it normal?
And what does the option "Take a new snapshot regardless of there were changes or not" means?

**Comment by Germar** [comment]
Overwriting a running system with old data can/will cause a system crash because you will overwrite essential files. I suggest to restore in a Live system

**Comment by Auronius** [comment]
Thank you, but I am not so skilled to make custom Live system images. Can you suggest Linux distro with Backintime preinstalled, so I could use it as Live image?

**Comment by Germar** [comment]
Sorry, I don't know which distro comes with BiT preinstalled. But with Ubuntu you can install it like you would do after installing Ubuntu on your drive:

```
sudo add-apt-repository ppa:bit-team/stable
sudo apt-get update
sudo apt-get install backintime-qt4
```

**Comment by Germar** [comment]
Oh, regarding `Take a new snapshot regardless of there were changes or not`:
Normally BiT does check if there where changes since last snapshot and will remove the new snapshot immediately if there where no changes. If this is checked it will keep the snapshot even if there where no changes.

But this is only with activated `Full rsync mode` (which is default with `1.2.0`). Without `Full rsync mode` BiT will run a `rsync --dry-run` first to check if there are changes and will only create a new snapshot if it found changes. If you deactivate `Check for changes` it will not run `rsync --dry-run` but always create a new snapshot.

**Comment by buhtz** [comment]
Close.
