### ISSUE TITLE
Password not getting cached

### ISSUE THREAD

**Issue by ghost** [bit-team/backintime#807]
I'm having this issue on two different machines, with two different versions of Debian and two different versions of BIT (which makes me think I'm doing something wrong!)

My installations:

Debian 9 (stretch), BIT 1.1.12-2 (from repository)
Debian 8 (Jessie), BIT 1.0.36-1 (from repository)

The issue is that the password is not getting cached after logout. When I enter the password, it is saved and scheduled cron snapshots work as long as I don't log out. After logout, the password is forgotten and cron jobs fail because it can't find the password. After logging in again, no password is showing on the config screen.

Have I missed something?

Thanks!

**Comment by buhtz** [comment]
I am not clear about what "password" you mean. Can you plesae go into more detailes at this point.
And what kind of backup-job snapshot you are running?

**Comment by zal42** [comment]
I'm doing SSH backups, and the password is the SSH private key password. What I want to do is to have BiT run automatically from a cron job. The issue is that password is not reliably remembered across logouts, so automatic runs may work for a bit, but will fail once I log off. The first time I run BiT manually after logging in, I am asked for the password and then automatic runs are fine without any password requests -- until I log out. Then they fail.

That's all the details I can provide at the moment, as right now I've uninstalled this from my machines out of frustration. This problem has me completely stumped. I've read everything I could, tried everything I could, and no joy. I'd love to make this work -- it would be the perfect answer to my backup needs!

**Comment by buhtz** [comment]
Now I understand a bit better. I am using SSH but wihtout a passphrase for the key-pair. But I am not familar with the SSH and key things. It is still a mysterium for me. So I am out here.

@Germar is much more an expert in that topic. Currently he is out of ressources. So we have to wait...

**Comment by buhtzz** [comment]
Close. Outdated. Not reproducible. "ghost" account.
