### ISSUE TITLE
Spaces in file names are converted to %20 leading to errors

### ISSUE THREAD

**Issue by rklemme** [bit-team/backintime#815]
Error message in window (path names truncated):

_Failed to open ".../Downloads/Avalon%20T.ttf"._

_Error when getting information for file '.../Downloads/Avalon%20T.ttf': No such file or directory._

**Comment by buhtz** [comment]
Can you please give some more informations. Did this happen while you made a snapshot? Manual or automatic (scheduled)? Why type of snapshot (Local, SSH, ...)? Which distribution you are using? What is your snapshot-device (Server, external USB drive, filesystem, ...?)

Please re-do it with `--debug` option and post the output here.

**Comment by rklemme** [comment]
Sorry for the incomplete report. Yes, the file exists. Snapshot was done manually. There were no issues when doing the snapshot. Snapshots are done locally on an USB disk. This is Xubuntu 16.04 LTS (see below).

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
$ uname -a
Linux babelfish 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

I can reproduce the error like this: USB drive is mounted, open backintime-qt4, select a snapshot, click on the home directory, click on the directory "Download" and then just click on the file name (which is shown correctly in the UI). Then in total three error dialogs pop up, the first two mention the odd file name with the converted spaces and the last one stating an IO error.

Debug output:

```
$ backintime-qt4 --debug
DEBUG: [common/backintime.py:509 arg_parse] Arguments: {'debug': True} | unknownArgs: []

Back In Time
Version: 1.1.12

Back In Time comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; type `backintime --license' for details.

DEBUG: [common/backintime.py:576 getConfig] config file: /home/robert/.config/backintime/config
DEBUG: [common/backintime.py:577 getConfig] profiles: ['1']
DEBUG: [common/pluginmanager.py:88 PluginManager.load_plugins] Register plugin path /usr/share/backintime/plugins
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin notifyplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin userscriptsplugin.py
DEBUG: [common/pluginmanager.py:104 PluginManager.load_plugins] Add plugin qt4plugin.py
DEBUG: [common/snapshots.py:947 Snapshots.has_old_snapshots] Found old snapshots: False
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.Gnome'
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
Thunar: Failed to open "/media/robert/Backup/robert/backintime/babelfish/robert/1/20170922-170816-487/backup/home/robert/Downloads/Avalon%20T.ttf": Error when getting information for file '/media/robert/Backup/robert/backintime/babelfish/robert/1/20170922-170816-487/backup/home/robert/Downloads/Avalon%20T.ttf': No such file or directory
DEBUG: [common/tools.py:611 keyring_supported] Found appropriate keyring 'keyring.backends.Gnome'
DEBUG: [common/mount.py:50 Mount.__init__] pw-cache is not running
DEBUG: [common/mount.py:59 Mount.__init__] Call command: /usr/bin/backintime pw-cache start
```

As a rough guess the issue looks like the file name is converted to a URI but then attempted to open the file part as is, which must fail, of course.

If you need more information please let me know. Again, sorry for the brief report.

**Comment by buhtz** [comment]
Just to be sure I understand you correct: The real filename in the filesystem is `Avalon T.ttf` (there is a blank space and not `%20`)?

What filesystem is on the USB stick?
Your Ubuntu uses ext4 for the system partitions?

**Comment by buhtz** [comment]
I did some testing. But I think I need assistance from @Germar because he is more familiar with the code.
![zwischenablage05](https://user-images.githubusercontent.com/11861496/31008444-715b6c98-a504-11e7-9a5f-c4aad4649d8e.png)

The magic happens here
https://github.com/bit-team/backintime/blob/918d01c68099bce7148d7936d71c2d5bfb8f9da1/qt/app.py#L1287

Please see also the Qt-docu about it:
http://doc.qt.io/qt-4.8/qurl.html#QUrl-4
and
http://doc.qt.io/qt-4.8/qurl.html#ParsingMode-enum

Now some thoughts and questions about it

1. Here a Qt component is used to open a file with its default application. Shouldn't we use Pythons own `os.startfile()` for that? https://docs.python.org/3.5/library/os.html#os.startfile This would be independ from plattform and external libraries. If this is not an option read the next points.
2. In the code there is an extra `"file://"` added to the file string. Interpreting the Qt-docu there is no need for that.
3. I am not familar with file-URIs. In my understand it shouldn't matter if a file-path or an uri is used. The URI should work. What is wrong on the conversion of the URI? Maybe there is a bug in Qt?
4. Read carefully the Error in the screenshot. There are two URIs. The first one (in bold) is different from the second one (`Avalon%2520T.ttf` -> `Avalon%20T.ttf`). Not sure which one was realy used for opening from the Qt-SDK.
5. What would happen if we switch to _parsing mode_ `QUrl::StrictMod`?

**Comment by rklemme** [comment]
Yes, your understanding is correct. There is a space in the filename.

All involved filesystems are Linux filesystems: root and home partitions are ext4 and the file system on USB drive is btrfs.

**Comment by rklemme** [comment]
Regarding item 3 of your list: there must be two API calls to access a file - one with a file name and one with a URI (a URI is a valid Linux file name as far as I can see). What I am assuming (without looking at the code) is this: in some place a URI is created for the file name and then the file API is used to access the file.

**Comment by Germar** [comment]
Not sure, but I think I fixed this in current master. Please doublecheck with 1.2.0~alpha from testing PPA.

**Comment by buhtz** [comment]
Sorry I should have made this earlier. Initial I checked with the debian-repository package. Now with the git-version itself it works without problems.
It is fixed in master and can be closed.

@rklemme Feel free to ask if you need help with installing the git version of backintime.

**Comment by rklemme** [comment]
@buhtz thank you for the offer but I will just wait until my next upgrade of the OS (18.04 LTS that will be).
