### ISSUE TITLE
Unable to backup simultaneously under the same host

### ISSUE THREAD

**Issue by Abelian-grape** [bit-team/backintime#828]
Is this a bug or something that can be configured?

Thanks

**Comment by Germar** [comment]
Please add more infos. Simultaneous backups from different user/clients to one host work fine as long as your destination host has enough resources to handle multiple rsync instances at once

**Comment by Abelian-grape** [comment]
Thanks for the reply! The commands are :
1) backintime --config <configfile> backup
2) ctrl-z  # pause
3) bg  # send to background
4) backintime --config <configfile> backup   # different source and destination directory

The warning message is "A backup is already running"; the second backintime call gets cancelled. Is there a way to get around this?

**Comment by Germar** [comment]
Even if you define different config files BiT will write locks into the same `~/.local/share/backintime`. That's why it fail in your case. Is there a special need for custom config files in your case? You can easily use profiles in one config and run those profiles simultaneously.

Alternative with current dev version 1.2.0 you can use `--share-path PATH` to use specify different pathes for both instances...

**Comment by buhtz** [comment]
Looks solved and can #closed.
