### ISSUE TITLE
How to cope with large files that gets added to regularly

### ISSUE THREAD

**Issue by colinl** [bit-team/backintime#855]
I am looking for suggestions on the most efficient way to cope with backing up large files that are added to regularly. I have a number of files that are sqldumps of databases that grow slowly over time as data are added to them. The files are around 300MB text files but only have a few MB added each week.  If I use BiT as is then the archive grows by GBs each time I backup.  I use BiT for backing up the rest of the system and find it ideal and ideally don't want to have to use a different (incremental) backup system just for those files.  Any ideas would be gratefully received.

**Comment by colintedford** [comment]
I think keeping few snapshots as Gary suggests is the best backintime 
can do in that situation.

If you want many snapshots, something like BorgBackup 
(https://borgbackup.readthedocs.io/) or Restic (https://restic.net/) 
should work better. They split each file into parts and compare those 
instead of the whole thing, so the backups only grow by the size of the 
changes. I was just researching them yesterday, so I can share more 
links if you want them.

**Comment by glyndon** [comment]
Another backup utility that keeps its data in chunks is Duplicati.
https://www.duplicati.com/
(note the spelling. There are a few tools with similar names.)

**Comment by colinl** [comment]
OK, thanks for the ideas. I will have a look at the suggestions.

**Comment by colinl** [comment]
In case anyone is interested I have solved this by using borgbackup to do a local de-duplicated backup of the files and then including this backup in my BIT backup.

**Comment by emtiu** [comment]
Hi, thanks for the discussion everyone. I'm closing this Issue, but the request for a feature to better support these situations is tracked in:
- #210
- #498
