### ISSUE TITLE
BackInTime unworkably slow viewing log file, and freezing.

### ISSUE THREAD

**Issue by MatNieuw** [bit-team/backintime#867]
On Mint 18.3 XFCE, my BIT backup as root fails after 2.5 hours; it appeared to reach the end, then because of some errors removed the created snapshot. So, I started it again with logging ¨all¨ . After failure, I tried viewing the log function of BIT, but one core (out of 6, 3.2 GHz AMD) pegged to 100% and BIT didn´t react anymore. I gave up after > 30 minutes, stopped BIT and as root killed the python3 process.
Examining the log, file /root/.local/share/backintime/takesnapshot_.log was 315 MByte. Xed could open it, but moving around was very slow. Glogg opened it in seconds, shows 3 M+ lines, and moving around was fast.
Can the ¨view log" feature not be re-implemented like glogg? This is a read-only viewer, which is what you want for a log. I suspect python is totally unsuited for this. I have saved the log, in case it´s handy.
In any case, the UI is totally dead while the log view is being created, I am not sure how easy it is to de-couple the UI from the log view task.

BTW, the error was that rsync couldn´t create some perl files using mkstemp. I´ve now set BIT to continue on error.

**Comment by MatNieuw** [comment]
Edit: BIT version 1.1.12

**Comment by Germar** [comment]
Version 1.2.0 got a complete rewrite of the log view. It is a lot faster now. ~450MB log file in ~30sec here...

**Comment by MatNieuw** [comment]
Thanks Germar, that´s quite acceptable.

**Comment by AndrewDavis** [comment]
I have roughly the same issue, except possibly not to do with the log. It may be the status pane at the bottom, or maybe it's just the resource allocation in my Linux Mint 19, but for whatever reason, while a snapshot is in progress, BIT and my filesystem both freeze up big time, for minutes at a time. If I e.g. hit pause, it takes a few minutes before it actually pauses and I can use my filesystem again. It also seems to be aggravated by switching the dropdown, either in the main window or the Settings window, to the profile having its snapshot taken.

I would expect to still be able to use my filesystem, even while BIT is operating at full speed, and to not have BIT freeze up on me for minutes at a time. This could perhaps be done by occasional sleep operations. It's also a stability issue for BIT and the backups it makes, because not being able to pause snapshots when needed has caused snapshots of mine to become corrupted, similar to MatNieuw's description. In one case, my system completely stopped responding, and I had to even force shutdown my computer, which also then required me to run chkdsk on my external hard drive in Windows...
