### ISSUE TITLE
Provide a CLI package

### ISSUE THREAD

**Issue by bernd-wechner** [bit-team/backintime#899]
Just a request. I love backintime and use it on my desktop. But would like to use it on servers as well, and see that it has a neat CLI interface. Alas I can't find a way to install just the CLI components, if I try (Ubuntu or Raspbian server):

$ sudo apt install backintime-common

it wants to install a load of QT4 stuff. I guess I could live with it but frankly seems like unnecessary lint on a server that has no desktop environment. 

To wit I think it would serve well if the CLI support were offered in a standalone package.

**Comment by mauromol** [comment]
I installed backintime-common package for version 1.0.10 of BIT (on a NAS with Debian Wheezy) but I didn't have to install anything about QT4. Maybe meanwhile some changes where made to the dependencies of backintime-common package?

**Comment by buhtzz** [comment]
@mauromol There is a new forming maintaining team and we do review all issues. Thanks for your report.

The Qt stuff is installed by default [not because it is not a hard dependency but a recommendation](https://packages.debian.org/unstable/backintime-common). I think recommended packages are installed also but don't have to. There must be an `apt-get` switch for it.

Find the switch and you can install the cli package alone. But keep in mind that currently the cli package alone is not able to create or modify an snapshot configuration. You can just start snapshot jobs.

Please let me ask you further: If you could wish. To create/modify snapthot jobs would prefer a strict CLI interface or a real [TUI](https://en.wikipedia.org/wiki/Text-based_user_interface)?

Tag: Feature, Low, "GUI"

**Comment by emtiu** [comment]
I agree :) Thanks for your thoughts. We'd like to have this feature, and we're tracking it as a Feature Request in #254. I'm closing this Issue as a duplicate.
