### ISSUE TITLE
Back In Time on Ubuntu 18.X

### ISSUE THREAD

**Issue by m2c2lure67** [bit-team/backintime#917]
I'm an extremely new newbie!  I've installed Back In Time, and pointed it to my GDrive files.  It has taken two successful snapshots; however, the second snapshot contains duplicates of unchanged files that are already contained in the original snapshot.  Am I misinformed as to how "snapshots" are supposed to work?

**Comment by plgruener** [comment]
Each snapshot should be a *complete* "copy" of all files present at the time of the backup-operation. I put that in quotes because Back In Time (as underlying rsync) uses hardlinks to deduplicate files (iirc that should be the default settings). So if you have not deleted said file, it should be present under both backintime/snapshot1 and backintime/snapshot2, but it should be the same file (you can verify via inode number, `ls -i` (does not seem to work for directories though))

**Comment by m2c2lure67** [comment]
I'm sorry to waste any of your time, but after this, and reviewing the Baobab results, I realized it only "looks" like it's duplicating data "externally", which brings us back to those hard-links you referred to...

Thanks Bunches&Bookoodles!

**Comment by plgruener** [comment]
So, is your problem resolved (if so, you should close this issue), or is BIT not working as intended?
I'm only another user, but happy to help.

**Comment by m2c2lure67** [comment]
Wow!  Open AND close my own issue(s)...this kind of power could go to my head.
