### ISSUE TITLE
Can I use Bit to synchronize two or more ubuntu maschines?

### ISSUE THREAD

**Issue by kerner1000** [bit-team/backintime#942]
I am currently syncing data using [unison](https://www.cis.upenn.edu/~bcpierce/unison/). I was wondering, if it would be possible to configure a Bit profile just for synchronization.

* Is this a 'stupid' idea, i.e., is there anything that speaks against that?
* Is there any (probably) unwanted side effects I should be aware of?

* Is it enough to configure under 'General -> Advanced' the same host, user, and profile name? If the storage path is the same as well, this would effectively work like a synchronization with an additional possibility to go "back in time".

**Comment by Germar** [comment]
This wouldn't syncronise your machines. It would just put backups of both machines in the same place. Which would end up in quite a chaos in my opinion. BiT is no syncing tool by design. You should rather use a different software like unison for the job. Also a syncing tool is no backup tool neither. There are scenarios that would cause lose of data if you use a syncing tool like unison for backups.

**Comment by noMICROSOFTbuhtz** [comment]
Sync is not backup.

I would recommend "Unison" for synchronization - but there are a lot more tools for this.
