### ISSUE TITLE
Question: how to donate money

### ISSUE THREAD

**Issue by Yvan-Masson** [bit-team/backintime#943]
Hi,

I really like your software! I consider it being the best for "normal people" on Linux, and is thus very important. I am not able to contribute to the source code, but I would be pleased to donate money: could you write somewhere if you accept money and how?

Best regards,
Yvan

**Comment by Germar** [comment]
Hi Yvan,

that's very kind of you. I had donation buttons in the README.md but I removed them some months ago because at the moment I barely find time to for BackInTime.

Here they are again:
Flattr:    [![Flattr this](https://button.flattr.com/flattr-badge-large.png)](https://flattr.com/submit/auto?fid=nw135z&url=https%3A%2F%2Fgithub.com%2Fbit-team%2Fbackintime)
PayPal: [![Donate PayPal](https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif)](https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=37PJBGSQL7DC2)

Kind regards,
Germar

**Comment by Yvan-Masson** [comment]
Thanks Germar,
Hopefully you will be able to add again these donation buttons to the README.md soon :-)

Regards,
Yvan

**Comment by Germar** [comment]
Thank you for the generous donation :blush:

**Comment by coderkun** [comment]
@Germar, would a donation help to finish the qt5 port (if not done already)?

**Comment by Germar** [comment]
@coderkun qt5 port is already done in master (version 1.2). I didn't release 1.2 stable yet because I had some more plans for that release. But I today I decided to shift them to version 1.3

I'll prepare the 1.2 release, soon :v:

**Comment by pizzadude** [comment]
@Germar So... are you still planning to release 1.2?

**Comment by graysky2** [comment]
I'd also like to ditch the python-pyqt4 and related packages.

**Comment by pizzadude** [comment]
Nice, it was released! Thanks!

**Comment by Bkucera** [comment]
@Germar felt obligated to donate after restoring a file which would have been costly to rewrite :+1: Thanks again
