### ISSUE TITLE
Reuse snapshots after reinstalling OS ? 

### ISSUE THREAD

**Issue by Sabilon** [bit-team/backintime#952]
I've just installed a new OS (before : Mint with BIT 1.1.24 / now : Manjaro with BIT 1.2.0 alpha). The user has the same name, same id (1000).

I use BIT to backup a whole hard drive to another local hard drive. Paths to these drives are the same on the new OS as the were on the previous install. On the new OS, I've restored BIT config from the last snapshot.

I was expecting that BIT would do a new incremental snaphot as if I was using the old OS.
But I observe that it duplicates every file instead of making hardlinks.

Any clue ?

**Comment by vezza** [comment]
Hi, i'm not an expert here but i think that it is correct that BIT duplicates every file in the new backup... I suppose that after the new system install you restored also /home, in this case you have the same files as the old system but with different blocks assigned on the hard disk... so BIT cannot create hard links to the old blocks

**Comment by Sabilon** [comment]
Hi Vezza,

The whole hard drive I backup with BIT is a luks parition mounted on /mnt/<name>. It has not changed (though soft links in my /home point to folders there, but imho this fact as nothing to do with the situation).

But you've pointed me to a possible explication : could the new system manage blocks on the hard drive on a different way than the old one ?

Still, is there a solution to my problem, other than erase the whole backup and start a new one ?

**Comment by glyndon** [comment]
Remember that it's actually the rsync program that's doing the backup work, and that BiT is just the overseer that tells rsync what to do. 
You can learn plenty about rsync from its manpages and documentation at samba.org
But, AFAIK, rsync concerns itself only with files - *as* files - and not with the particular blocks of storage, and so it is agnostic regarding filesystems. 
When rsync replicates a new snapshot, it has the ability to create a hardlink to the prior copy of a file, in order to not waste space duplicating the whole file. That is why each snap appears to contain everything. It does, but it isn't a complete copy of all the data. That's the feature that relies on the file system to support the use of hardlinks.

**Comment by Sabilon** [comment]
Hi glyndon,

Thank you for your insight. Indeed, the one thing I have to understand is why rsync considers that all files have changed, when none has. Or it might consider that all files are new ?

**Comment by glyndon** [comment]
What happens is that rsync creates something for every file. If the file is different, it copies the whole file, and creates a new link (filename in a directory) pointing to that new copy. If the file has not changed (based on the criteria you choose through BiT), then rsync creates a link pointing to the copy of the file it already has on the destination. New links don't take any appreciable space on their own. 

Think of it as a very expensive book in the library that is relevant to fifteen different subject areas.
Rather than keep fifteen copies of the book, one in each subject's shelf area, the library just keeps one copy of the book (doesn't matter in which area's shelf it gets stored) and creates 15 index cards in the catalog. (I may be dating myself here, since libraries don't keep cards in catalogs anymore, but the same thing works with online catalogs) All the catalog cards point to the location of the one copy of the book, though the cards are located within the relevant subject areas of the catalog. So if you go looking for it under subject A, you'll get the same book as if you look for it under subject B. Saves space on the shelf, and cost.

The advantage to rsync making all those links to files that have not changed is that when you want to restore, each snapshot appears to contain *every* file. Easy to fetch! The fact that only one actual copy is stored, despite being pointed to from within many snapshots, makes this efficient for storage cost, and easy to use at the same time.

**Comment by Sabilon** [comment]
colinl : Yes they do appear. The strange thing is that everything *seems* to be exactly the same as if I was using my old system. Only that a new snapshot on the new system takes ages to do (1.5Tb of copying, instead of hard-linking), and would not end anyway, because the destination has not enough free space.

Another way of describing the same is : given a file `example.txt` on the source, `stat -c %h` on the same file in a snapshot made by the old system gives me some number > 1. This is expected because it is present in various snapshots, each copy hard-linked to the first backup. But `stat -c %h` on any file within the current snapshot being made on the new system gives 1, meaning it's a new copy.

**Comment by Sabilon** [comment]
`Use checksum to detect changes` is the only option that seems to alter the way BiT judges whether a file has changed, that is, if it makes a hardlink or a new copy. It is unchecked in my setup.

**Comment by glyndon** [comment]
I don't normally turn on 'use checksum' either, because detecting name/date/time/size is usually sufficient.
In your case, that it is making a new copy instead of just linking, suggests that it hasn't recognized the existing backup directory hierarchy as valid, and so doesn't 'see' that most of those files are already there.
Confirm that you can inspect all the prior snapshots using the BiT GUI before initiating a new backup. If BiT isn't showing them all, then it's pointing somewhere it shouldn't be.

**Comment by glyndon** [comment]
Oh, that reminds me: Double-check the timezone setting in your fresh OS install. If the files look like they are from a different time, then rsync might use that as a trigger to re-copy them. 
View a directory of files you know haven't changed, then look at the same one (using a shell, not BiT) in your backup filesystem, and see if they all differ by (e.g.) a uniform number of hours.

**Comment by Sabilon** [comment]
Solved ! Though it is not completely clear how ;)

I checked the timezone, everything was ok. Then I checked group ownership. I observed that :

- gid for the group named after the user is 1001 on Manjaro, while on Mint it is 1000. So all files seen from the new system (Manjaro) had a wrong group ownership (1000 is group 'autologin') : source files had gid 1000, but also the files in the snapshots. It is not clear to me if this caused the problem, because anyway rsync was seeing the same (wrong) group ownership on the source and the destination.
- group rights on files were heterogeneous. On the source, some were r-, other rw. On the destination, most files (probably all) were r-. I understand that BiT changes file ownership on the destination, so this is probably expected.

So I did a `chown -R :1001` and a `chmod -R g-w` on the source and on the snapshots. Done. BiT is now building a new snapshot as expected, making hardlinks on unchanged files (repeated `du -c --max-depth=1` on the parent folder of the snapshots demonstrates it clearly, as it only counts hard links once).

I'm not sure if only one of the two actions a did solved the problem, or if both were necessary ;)

Thank you glyndon and colinl for your help. I you have the answer, i'd be glad to understand exactly what was *sufficient and necessary* ;)

**Comment by glyndon** [comment]
Glad you have it working now. 
It's hard to tell from here with any certainty, but I'll guess that the fix was adjusting the GID on the target filespace to match the (new) source GID.

**Comment by Sabilon** [comment]
The thing is there was no new source GID ;) All were 1000 as the install of the new OS did not have any effect on the source (a different drive than the OS), other than the fact that new files were made with GID 1001.

**Comment by glyndon** [comment]
Oh, then I've no useful hypothesis re which action cured it for you, just glad something did.
