### ISSUE TITLE
Smart remove for intervals shorter than 1 day

### ISSUE THREAD

**Issue by lamyergeier** [bit-team/backintime#958]
I use Backintime to backup my computer codes. So I would like it to be backed up every 5 minutes incrementally but remove the snapshots older than 1 hour. Is it possible?

Also, is it possible to do incremental backup? (rsync is differential backup)

**Comment by glyndon** [comment]
To your second question:
The nature of rsync's backup is such that the concept of 'incremental' and 'differential' are irrelevant. Every backup *appears* to be a complete copy (very conveninent at restore-time), but thanks to rsync's ability to create hard links instead of redundant copies (when the file hasn't changed) no space is wasted.

**Comment by colintedford** [comment]
To your first question:

To backup every 5 minutes, open the settings, and on the General tab, 
in the Schedule section, you can choose 5 minutes.

In settings on the Auto-remove tab you will find the "Older than" 
option, but the shortest time you can set it to is 1 day. You could try 
setting it for 0.0417 days (about an hour), but I don't know if it will 
accept that.

You may be able to set a shorter auto-remove time by using the 
command-line version. The man page lists a remove command (in the 
COMMANDS section) which lets you remove specific snapshots. Someone 
else will have to explain how to identify which snapshots are older 
than an hour, but then you can set a cron job to run the find and 
remove commands on the schedule you want.

**Comment by buhtz** [comment]
Maybe the opener @lamyergeier can add something new to the discussion?

It seems to be a rare case to have remove intervals shorter than one day. Also running a backup every 5 minutes but remove backups older than 1 our smells like file syncing instead of a backup solution. In my understanding this use case is out of scope for BIT. NextCloud and Co are better suited here.

And only one persons requests the feature. IMHO the cost (code modifications and time resources) doesn't weight the benefit.
Also regarding the resources of the maintenance team I don't see when this feature would be implemented.

If there is no new contributor to implement this feature I would vote to close that Issue.

**Comment by buhtz** [comment]
Please feel free to re-open the issue, add more information or as further questions.
