### ISSUE TITLE
Backups not incremental after migration to new host

### ISSUE THREAD

**Issue by deshmukhs** [bit-team/backintime#961]
On my Ubuntu computer I used earlier, I had backed my files using backintime on an external hard disk.

When I connected the harddisk to my Manjaro installation, it could not detect the backups because:
    
- Backup path was different. It was /media/… on Ubuntu but /run/media/… on Manjaro

- Hostname was different. Earlier computer had ubuntu as hostname. Now, it is manjaro

So, in the settings, I made the necessary changes and now I can see all the backups and I have restored the necessary files.

However, when I take a fresh backup, it copies all the files over. Ideally, it should copy only the modified files. The new backup directory does not have any links to previous directories.

How do I make backintime to backup only modified files?

**Comment by dsimila** [comment]
I have hit the same bug, except installing antergos instead of manjaro (also an arch distro), and got the same problem.
I can't get hard linking to work now. 
File system is localy mounted ext4 on external 1 TB usb harddrive, hard links works when making them with ln or cp.
The user names and groups names are same, also user and group numbers are same.
I've set the same mount point. I even changed back the hostname to same as previuos name.

I've got incremental backups going all the way back to 2010 but now it just tries to do a full new copy and errors becouse disk full.

Stuff to back up is one users home directory containing ~300 GB of photographs + email and stuff.

**Comment by casipw** [comment]
I had the same issue on Arch Linux, using the backintime GUI from the AUR package `backintime-git`. It skipped the comparison step and began copying all files right away.

The GUI version from the AUR package `backintime` ran into #964/#965.

**The command line version worked for me: `sudo backintime --profile <profile name> backup`**

(using with the package `backintime`, haven't tested it with `backintime-git`)

**Comment by dsimila** [comment]
Weirdly incremental backups works on command line. 
$> backintime backup # super fast and all good ~370 GB and inode numbers match with previous backups.
So problem is apparently in backintime-qt.

**Comment by emtiu** [comment]
Hi, thanks for your reports! We're sorting out old Issues after a maintenance downtime. Can you provide any more insight what happened afterwards? Did you solve the problem, or did it continue?

**Comment by buhtz** [comment]
I'm sorry, the issue is quit old. But maybe it is still possible for you to reproduce the problem with the latest BIT release 1.3.3?

**Comment by buhtz** [comment]
Can anyone provide new information to this Issue?
Is it possible to reproduce the problem with the latest version 1.3.3 of BIT?

Otherwise the issue will be closed because we don't have enough information to reproduce the problem.

**Comment by emtiu** [comment]
Ugh, tricky. A bunch of users have hit this issue, but it was all years ago, and we have no feedback. I'd say we close and hope it doesn't come up again.
